.github/workflows/master_push.yml
The InVision DSM release process requires a token to deploy to InVision. This token would be exposed on pull requests from forks which could lead it to being misused. For now I am removing it from the pipeline until we can find a more secure way to handle it.
=> ci(invision-dsm): removes invision release step from master workflow

projects/canopy/src/lib/breadcrumb/breadcrumb-item/breadcrumb-item.component.html, projects/canopy/src/lib/breadcrumb/breadcrumb-item/breadcrumb-item.component.scss, projects/canopy/src/lib/breadcrumb/breadcrumb-item/breadcrumb-item.component.spec.ts, projects/canopy/src/lib/breadcrumb/breadcrumb-item/breadcrumb-item.component.ts, projects/canopy/src/lib/breadcrumb/breadcrumb.notes.ts
Consuming apps are getting ExpressionChangedAfterItHasBeenCheck errors from dynamic HostBindings which sets the class. In hindsight we should have been consistent for this component and just removed all dynamic Hostbindings which set classes. Slightly unnerving is the inability for storybook to replicate the errors consuming applications are getting even with our Async story.
Fixes: Similar issue to #3 however this is not replicable in storybook but has been evident in consuming apps. The same approach has been taken though which is removing the dynamic HostBinding which triggers the ExpressionChangedAfterItHasBeenCheck errors. 
Storybook link: https://deploy-preview-9--legal-and-general-canopy.netlify.app/?path=/story/components-breadcrumb--asynchronous-loading
=> fix(breadcrumb): hide icons expression changed

projects/canopy/src/styles/mixins.scss, projects/canopy/src/styles/typography.notes.ts, projects/canopy/src/styles/typography.scss, projects/canopy/src/styles/typography.stories.ts, projects/canopy/src/styles/variables/_typography.scss
Font style classes now have the addition of a `--strong` modifier. Not currently used in any components but added to allow more flexible typography within applications.
Minor line height modifications to match designs.
Co-authored with @alexcanning.
=> Typography changes

projects/canopy/src/lib/quick-action/quick-action.stories.ts, projects/canopy/src/styles/variables/components/_quick-action.scss
A quick actions visited link colour should match its unvisited colour
This is the same fix as https://github.com/canopy-collective/canopy/pull/403
=> fix(quick-link): fixed visited link colour

projects/canopy/src/lib/spacing/margin/margin.notes.ts
Adds missing docs for the missing horizontal and vertical margin directives
=> docs(margin): add missing docs for margin directives

projects/canopy/src/lib/spacing/padding/padding.notes.ts
Adds missing horizontal and vertical padding directives to docs
=> docs(padding): adds missing directives to docs

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/forms/radio/index.ts, projects/canopy/src/lib/forms/radio/radio-button--filter.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.html, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio-group.component.html, projects/canopy/src/lib/forms/radio/radio-group.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-group.component.ts, projects/canopy/src/lib/forms/radio/radio.interface.ts, projects/canopy/src/lib/forms/radio/radio.module.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/forms/radio/radio.stories.ts, projects/canopy/src/styles/variables.scss, projects/canopy/src/styles/variables/components/_filter-button.scss
add filter button variant to radio comp
Add filter button 'select-one' variant as a variant for the existing Radio component.
Storybook link: [https://deploy-preview-36--legal-and-general-canopy.netlify.app/?path=/story/components-filter-button--select-one](https://deploy-preview-36--legal-and-general-canopy.netlify.app/?path=/story/components-filter-button--select-one)
Design link: [https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/432421864_Filter_Buttons](https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/432421864_Filter_Buttons)
Screenshot:
=> feat(filter-button): add filter button variant to radio comp

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.html, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.scss, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.spec.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.interface.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.notes.ts, projects/canopy/src/lib/forms/checkbox-group/filter-group.stories.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/forms/toggle/checkbox.stories.ts, projects/canopy/src/lib/forms/toggle/index.ts, projects/canopy/src/lib/forms/toggle/switch.stories.ts, projects/canopy/src/lib/forms/toggle/toggle--filter.component.scss, projects/canopy/src/lib/forms/toggle/toggle--switch.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.html, projects/canopy/src/lib/forms/toggle/toggle.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.spec.ts, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/toggle/toggle.interface.ts, projects/canopy/src/lib/forms/toggle/toggle.module.ts, projects/canopy/src/lib/forms/toggle/toggle.notes.ts, projects/canopy/src/lib/forms/toggle/toggle.stories.common.ts, projects/canopy/src/lib/forms/validation/form.stories.ts
add filter variant to checkbox group and toggle
Adds filter variant to `checkbox group` and to `toggle` components, for filter group with multiple selections.
Storybook link: [https://deploy-preview-41--legal-and-general-canopy.netlify.app/?path=/story/components-filter-buttons--select-multiple](https://deploy-preview-41--legal-and-general-canopy.netlify.app/?path=/story/components-filter-buttons--select-multiple)
Design link: [https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/screens/432421864_Filter_Buttons](https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/screens/432421864_Filter_Buttons)
Screenshot:
=> feat(filter-button): add filter variant to checkbox group and toggle

projects/canopy/src/lib/forms/input/input.scss, projects/canopy/src/lib/forms/select/select.scss, projects/canopy/src/styles/variables.scss, projects/canopy/src/styles/variables/_main.scss, projects/canopy/src/styles/variables/components/_input.scss, projects/canopy/src/styles/variables/components/_select.scss, projects/canopy/src/styles/variables/components/button/_button.scss
Fixes an issue where inputs were set at the wrong height (50px) instead of the height specified in the designs (44px).
Fixes #43
Storybook link: https://deploy-preview-45--legal-and-general-canopy.netlify.app/
Design link: https://legalandgeneral.invisionapp.com/d/main#/console/19910472/416751159/inspect
Screenshot:
=> fix(input): match height with designs

projects/canopy/src/lib/forms/index.ts, projects/canopy/src/lib/forms/radio/radio-button--filter.component.scss, projects/canopy/src/styles/variables/components/_filter-button.scss
Amend filter buttons style by getting rid of 'max-height' because it's not necessary and using 'line-height' instead, and add
checkbox-group to forms index.ts.
Storybook link: [https://deploy-preview-50--legal-and-general-canopy.netlify.app/?path=/story/components-filter-buttons--select-one](https://deploy-preview-50--legal-and-general-canopy.netlify.app/?path=/story/components-filter-buttons--select-one)
Design link: [https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/432421864_Filter_Buttons](https://legalandgeneral.invisionapp.com/share/2SZ192MTHZY#/432421864_Filter_Buttons)
=> refactor(filter-buttons): amend filter buttons style and public-api

.storybook/canopy-theme.js
Adds the logo to the storybook header, just to make it a bit more on brand. The image was already in the repo so just a case of linking to it.
=> docs: adds brand logo to storybook

projects/canopy/src/lib/forms/toggle/toggle.component.html, projects/canopy/src/lib/forms/toggle/toggle.component.spec.ts
Removes the empty aria-describedby attribute from the input element when it is null.
Fixes #56
=> fix(toggle): remove empty describedby attribute when value is null

angular.json
Sets the preference for sending usage analytics to Angular to "No".
No testing required as it just prevents Angular's analytics.
=> build(angular): set preference for sending analytics to angular

projects/canopy/src/styles/color.stories.ts, projects/canopy/src/styles/grid.stories.ts, projects/canopy/src/styles/mixins.stories.ts, projects/canopy/src/styles/spacing.stories.ts, projects/canopy/src/styles/typography.stories.ts, projects/canopy/src/styles/utils.stories.ts
As recommended by Storybook, this changes some stories into the CSF story format.
Note that it only changes the CSS based stories found in the styles directory.
There are a few more stories that need converting, but require a little more thought, e.g. Pipes, Directives.
Partly addresses #65 
There should be no changes to the functionality in Storybook, as this is more of a future proofing change.
Storybook link: https://deploy-preview-67--legal-and-general-canopy.netlify.app/
=> refactor(stories): convert CSS stories to CSF format

projects/canopy/src/lib/forms/date/date-field.component.spec.ts, projects/canopy/src/lib/forms/date/date-field.component.ts
The `writeValue` method gets called before `ngOnInit`, this was causing an error to be thrown as the `formGroup` wasn't yet defined. The unit test was masking this issue because `detectChanges` was called before a value was supplied, the value was then supplied after initialisation with a subsequent `detectChanges` call to pre-populate the fields. The change to the unit test in this commit should safeguard against regression.
fixes #71
The existing version is here, where the form fields are not pre-populated with the value.
https://legal-and-general-canopy.netlify.app/?path=/story/components-form-date-input--standard
The latest version is here, where the form fields are pre-populating correctly
https://deploy-preview-72--legal-and-general-canopy.netlify.app/?path=/story/components-form-dat …
=> fix(date-field): fixes issue with value not pre-populating

projects/canopy/src/lib/brand-icon/brand-icon.component.ts, projects/canopy/src/lib/icon/icon.component.ts
Just a minor refactor.
The BrandIcon had a duplicate injected `ElementRef`, I removed one.
I also aligned the injected `ElementRef` variable to be called `hostElement`, this aligns with the majority of other components. I think it is a more descriptive name as there could be multiple elementRefs and hostElement gives a bit more context as to what element it is.
=> Brand icon remove duplicate variable

projects/canopy/src/lib/forms/input/input.notes.ts
Apologies I had a few markdown formatting issues in the notes.
=> docs(input): fixes markdown formatting

.github/CODEOWNERS
Using the team name should reduce steps to keep in sync as we add more people.
=> ci(codeowners): updates CODEOWNERS to use team name

projects/canopy/src/lib/forms/toggle/toggle.component.scss
The checkbox icon colour was set to be white when unchecked causing issues
when a background is present.
Storybook link: https://deploy-preview-92--legal-and-general-canopy.netlify.app/
Screenshot:
=> fix(checkbox): fix the checkbox icon colour

projects/canopy/src/lib/forms/input/input-field.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/select/select-field.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.scss
The `background-color` of the form fields was applied to the wrong elements. I've now moved it to the input tags.
Screenshot:
(Ignore the text colour against the background as i picked the first colour available in storybook)
=> fix(forms): fix bg colour on form fields

.github/workflows/master_push.yml, .releaserc, docs/CONTRIBUTING.md, docs/NEXT_BRANCH.md
The `next` branch allows the library to be published with a pre-release version. 
Release major versions of the library without blocking other teams.
=> ci(next): add capability to release next branch

projects/canopy/src/lib/table/table-cell/table-cell.component.html, projects/canopy/src/lib/table/table-cell/table-cell.component.spec.ts, projects/canopy/src/lib/table/table-cell/table-cell.component.ts, projects/canopy/src/lib/table/table-head-cell/table-head-cell.component.ts, projects/canopy/src/lib/table/table.interface.ts, projects/canopy/src/lib/table/table.notes.ts, projects/canopy/src/lib/table/table.stories.ts, projects/canopy/src/lib/table/table/table.component.spec.ts, projects/canopy/src/lib/table/table/table.component.ts
Adds the ability to configure whether the contents of a `table-head-cell` are displayed in each row on mobile. This is useful for the project I'm working on where the first column's value is long and self explanatory.
The default value for `showLabel` is true, but if set to false, the label is visually hidden; so it is still available to screen readers but not on screen.
The story has a new knob for toggling the label on the Author column of the example table.
1. Set viewport in Story to mobile.
2. Set `Display author label on mobile` to false
3. Observe that label for *Author* does not appear in each row
4. Set `Display author label on mobile` to true
5. Observe that label for *Author* appears in each row
Storybook link:
=> feat(table): add configurable showLabel property

projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.spec.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.ts
Calling `form.reset()` from the parent form failed to uncheck the checked child toggle components.
So I have updated the `value` setter to uncheck all children when an empty array is passed in.
=> fix(checkbox-group): uncheck child toggles when parent form is reset

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/forms/radio/radio-button--segment.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio-group--segment.component.scss, projects/canopy/src/lib/forms/radio/radio-group.component.html, projects/canopy/src/lib/forms/radio/radio-group.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-group.component.ts, projects/canopy/src/lib/forms/radio/radio.interface.ts, projects/canopy/src/lib/forms/radio/radio.module.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/forms/radio/segment.stories.ts, projects/canopy/src/lib/forms/toggle/index.ts, projects/canopy/src/styles/form.scss, projects/canopy/src/styles/variables.scss, projects/canopy/src/styles/variables/components/_radio.scss
This PR implements the segment component. The way the segment stack is controlled by the `stack` input which by default is set to be falsey.
The segment component should be either inline at all breakpoints or stack whenever needed (sm, md, lg breakpoint).
It takes the full width of the container element.
Storybook link: https://deploy-preview-86--legal-and-general-canopy.netlify.app/
Design link: https://legalandgeneral.invisionapp.com/share/NSZDSDYUWFE#/screens/416751156_Segment
Screenshots:
=> feat(segment): add segment component

.github/workflows/pull_request.yml, package-lock.json, projects/canopy/package.json
Currently the `next` branch gets triggered both on push and on PR open/sync. This PR updates the `pull-request.yml` workflow so that it ignores the `next` branch. That means that anytime a change is pushed to the `next` branch a new pre-release will be created (hopefully with the correct tag x.x.x-next.y).
This also updates the `peerDependencies` of Angular to match the newest version and updates the dependencies by running `audit fix`.
=> Fix issues with `next` branch / Angular 11 upgrade

.releaserc
After creating the `next` branch with the Angular upgrade I've noticed that the version was set to `4.0.0` instead of `4.0.0-next.1`. 
The documentation says that if we set `"prerelease": true` this will take the name of the branch which did not happen in our case 🤔  I have updated the config to be more specific `"prerelease": "next"` hoping that this fixes the issue.
More info here: https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#prerelease
I've also added the `channel` property which will allow users to install using the `@next` tag.
=> ci(semantic-release): update config to create pre-releases

projects/canopy/src/lib/forms/input/input-field.component.html, projects/canopy/src/lib/forms/input/input-field.component.spec.ts, projects/canopy/src/lib/forms/input/input-field.component.ts, projects/canopy/src/lib/forms/input/input.notes.ts, projects/canopy/src/lib/forms/input/input.stories.ts
Add an input to the `inputField` to show or visually hide the label. 
This is required when the label has to be visually hidden - for example an input within a table row.
Fixes #109
=> fix(input-field): add showLabel to the input field

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/card/card-footer/card-footer.component.html, projects/canopy/src/lib/card/card-footer/card-footer.component.scss, projects/canopy/src/lib/card/card-footer/card-footer.component.spec.ts, projects/canopy/src/lib/card/card-footer/card-footer.component.ts, projects/canopy/src/lib/card/card-header/card-header.component.html, projects/canopy/src/lib/card/card-header/card-header.component.scss, projects/canopy/src/lib/card/card-principle-data-point/card-principle-data-point.component.scss, projects/canopy/src/lib/card/card.component.html, projects/canopy/src/lib/card/card.component.spec.ts, projects/canopy/src/lib/card/card.component.ts, projects/canopy/src/lib/card/card.module.ts, projects/canopy/src/lib/card/card.notes.ts, projects/canopy/src/lib/card/card.stories.ts, projects/canopy/src/lib/feature-toggle/feature-toggle.stories.ts, projects/canopy/src/lib/grid/grid.stories.ts, projects/canopy/src/lib/hero/hero.stories.ts, projects/canopy/src/lib/page/page.notes.ts, projects/canopy/src/lib/page/page.stories.ts, projects/canopy/src/lib/spacing/margin/margin.notes.ts, projects/canopy/src/lib/spacing/margin/margin.stories.ts, projects/canopy/src/lib/spacing/padding/padding.notes.ts, projects/canopy/src/lib/spacing/padding/padding.stories.ts
Adds the 'form-journey' card type to the already existing cards.
FYI: The desktop version will be slightly different from the design version as we opted to use the existing grid for page positioning and card width.
The product card was changed to use card-content instead of card-header, and the card-header suffered minor modifications.
All the other cards examples look exactly the same and did not suffer design modifications.
Design link: [https://legalandgeneral.invisionapp.com/share/J4ZQ1VDY96K#/436223077_AN_03-0_ChangeBankOutsideWindow_Annuity_XL](https://legalandgeneral.invisionapp.com/share/J4ZQ1VDY96K#/436223077_AN_03-0_ChangeBankOutsideWindow_Annuity_XL) …
=> feat(card): add form journey card type

projects/canopy/src/lib/forms/input/input-field.component.spec.ts, projects/canopy/src/lib/forms/input/input-field.component.ts, projects/canopy/src/lib/forms/input/input.directive.ts
Update logic so that when the input itself has an error the parent will get the
error class too.
Reason being that we are using the input field in a table and can’t put the validation component in the same cell, but still want the field highlighted red when invalid.
Storybook link: https://deploy-preview-129--legal-and-general-canopy.netlify.app/?path=/story/components-form-form-validation--standard
=> fix(input-field): update error class logic

projects/canopy/src/lib/accordion/accordion-panel-heading/accordion-panel-heading.component.scss, projects/canopy/src/lib/button/button.component.scss, projects/canopy/src/lib/card/card-title/card-title.component.scss, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.scss, projects/canopy/src/lib/footer/footer.component.scss, projects/canopy/src/lib/forms/date/date-field.component.scss, projects/canopy/src/lib/forms/hint/hint.component.scss, projects/canopy/src/lib/forms/input/input-field.component.scss, projects/canopy/src/lib/forms/label/label.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/select/select-field.component.scss, projects/canopy/src/lib/forms/select/select.scss, projects/canopy/src/lib/forms/sort-code/sort-code.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.scss, projects/canopy/src/styles/color.stories.ts, projects/canopy/src/styles/typography.scss
Somewhere along the way we removed some css variables but didn't update all of the components that used them. We haven't had any issues raised from a styling point of view so for now I just removed all of the references as opposed to researching where they were individually removed. I can't foresee any unintended consequences. 
We could potentially do some work to prevent this happening again, but for now I've just done the minimal amount to clear the bug out of the way.
Fixes #80
=> Remove references to non-existent css variables

projects/canopy/src/lib/table/table-cell/table-cell.component.scss, projects/canopy/src/lib/table/table-head-cell/table-head-cell.component.scss, projects/canopy/src/lib/table/table-head/table-head.component.scss, projects/canopy/src/lib/table/table-row-toggle/table-row-toggle.component.scss, projects/canopy/src/lib/table/table-row/table-row.component.scss, projects/canopy/src/lib/table/table.breakpoints.scss, projects/canopy/src/lib/table/table.interface.ts, projects/canopy/src/lib/table/table.notes.ts, projects/canopy/src/lib/table/table.stories.ts, projects/canopy/src/lib/table/table/table.component.scss, projects/canopy/src/lib/table/table/table.component.spec.ts, projects/canopy/src/lib/table/table/table.component.ts
The LgTable currently always uses the non-mobile layout at and above the `md` breakpoint. However, if the table is placed in a container that does not fill the width of the screen then it can be desirable to show the mobile layout at larger screen widths.
This PR adds a new input which allows the consumer to specify at which breakpoint the full size layout should be displayed: 
`[fullSizeBp]="'sm'"` or `[fullSizeBp]="'md'"` or `[fullSizeBp]="'lg'"`
It defaults to using `md` if not provided, so should not introduce a breaking change. I also improved the LgTable storybook Knobs to make them easier to use.
Storybook link: https://deploy-preview-146--legal-and-general-canopy.netlify.app/
=> feat(table): add configurable fullSizeBp setting

projects/canopy/src/styles/spacing.scss
When using LgPadding and LgMargin, the styles applied by the directives can be overridden as they
have low specificity. It was agreed that they should make use of !important to overcome this. For details see the issue discussion: #49
Fixes #49
To test, I suggest checking that the padding and margin directives all still work as expected in story book. As a step further, you could import a build from this branch into your project and check it there too. 
=> fix(spacing): add !important to all lgMargin and lgPadding classes

package.json, projects/canopy/src/lib/table/table-row/table-row.component.spec.ts, projects/canopy/src/lib/table/table-row/table-row.component.ts, projects/canopy/src/lib/table/table.interface.ts, projects/canopy/src/lib/table/table.notes.ts, projects/canopy/src/lib/table/table.stories.ts, projects/canopy/src/lib/table/table/table.component.scss, projects/canopy/src/lib/table/table/table.component.spec.ts, projects/canopy/src/lib/table/table/table.component.ts, projects/canopy/src/styles/variables/components/_table.scss
Add a new `variant` input to the table to cater for a new alternative style. This style will be mainly used to overcome accessibility issues when the text is a lighter colour (for example with the blue links).
Storybook link: https://deploy-preview-155--legal-and-general-canopy.netlify.app/?path=/story/components-table--standard
Screenshots:
Expandable table:
Regular table:
=> feat(table): add variant input to table

docs/CONTRIBUTING.md, docs/USAGE.md
Found some old Netlify links and updated them with the new one: https://legal-and-general-canopy.netlify.app/
=> Update old storybook links

projects/canopy/src/lib/table/table-cell/table-cell.component.scss, projects/canopy/src/lib/table/table.stories.ts
Fixes an alignment issue when a table column's header label wraps onto multiple lines in the non-column (aka mobile) layout.
Fixes #108 
Screenshot:
- *N/A* I have provided an adequate amount of test coverage
- *N/A* I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- *N/A* I have provided a story in storybook to document the changes
- *N/A* I have provided documentation in the notes section of the story
- *N/A* I have added any new public feature modules to public-api.ts
- *N/A* I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)
=> feat(table): align items to center - not baseline - in table cell

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/alert/alert.notes.ts, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.html, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.scss, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.ts, projects/canopy/src/lib/details/details.component.scss, projects/canopy/src/lib/details/details.component.spec.ts, projects/canopy/src/lib/details/details.component.ts, projects/canopy/src/lib/details/details.interface.ts, projects/canopy/src/lib/details/details.module.ts, projects/canopy/src/lib/details/details.notes.ts, projects/canopy/src/lib/details/details.stories.ts, projects/canopy/src/styles/variables/components/_details.scss
Adds the same variants to the Details component that can be used with the Alert component. Also automatically sets the ARIA role to "alert" for specific variants, and adds an icon to the panel heading component if applicable.
Storybook link: https://deploy-preview-169--legal-and-general-canopy.netlify.app/?path=/story/components-details--standard
Design:
Screenshot:
=> Details component updates

package.json
Bumps [commitizen](https://github.com/commitizen/cz-cli) from 4.2.1 to 4.2.3.
=> build(commitizen): bump commitizen from 4.2.1 to 4.2.3

projects/canopy/src/lib/table/table-cell/table-cell.component.scss, projects/canopy/src/lib/table/table-expanded-detail/table-expanded-detail.component.scss, projects/canopy/src/lib/table/table-expanded-detail/table-expanded-detail.component.ts
We found a bug where on mobile long table cell labels were too close to the table cell value. In addition to that the table cell was wrapping so I've set the table cell content to never do that since the table cell value should always be short.
Before:
After:
=> fix(table): update spacing styles of cells on small devices

docs/CONTRIBUTING.md, projects/canopy/src/lib/pipes/camel-case/camel-case.pipe.ts
Apparently there was another instance of the insufficient regular expression.
I've also fixed a typo spotted by Alex C.
=> fix(code-ql): update camel case pipe regex

.github/dependabot.yml, .gitignore
The current `"@storybook/*"` should work but it doesn't. I've found another person with the same issue but no answer.
I've updated the current list to be more specific which hopefully should work.
In addition to that I've modified the `.gitignore` to cover the nested node modules.
=> Fix issue with Dependabot ignore list

projects/canopy/src/lib/forms/radio/radio-button--segment.component.scss, projects/canopy/src/lib/forms/radio/radio-group--segment.component.scss, projects/canopy/src/lib/forms/validation/form.stories.ts
Update error styles for segment as incorrect.
Storybook link: https://deploy-preview-216--legal-and-general-canopy.netlify.app/?path=/story/components-form-form-validation--standard
Screenshot before:
Screenshot after:
=> fix(segment): update style for error state

projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.html, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.spec.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.module.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.notes.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.stories.ts, projects/canopy/src/lib/forms/date/date-field.component.html, projects/canopy/src/lib/forms/date/date-field.component.spec.ts, projects/canopy/src/lib/forms/date/date-field.component.ts, projects/canopy/src/lib/forms/date/date-field.module.ts, projects/canopy/src/lib/forms/date/date-field.notes.ts, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio-group.component.html, projects/canopy/src/lib/forms/radio/radio-group.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-group.component.ts, projects/canopy/src/lib/forms/radio/radio.module.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/forms/radio/segment.stories.ts, projects/canopy/src/lib/forms/select/select.directive.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.html, projects/canopy/src/lib/forms/sort-code/sort-code.component.ts, projects/canopy/src/lib/forms/sort-code/sort-code.module.ts, projects/canopy/src/lib/forms/sort-code/sort-code.notes.ts, projects/canopy/src/lib/forms/sort-code/sort-code.stories.ts, projects/canopy/src/lib/forms/toggle/toggle.component.html, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/toggle/toggle.module.ts, projects/canopy/src/lib/forms/toggle/toggle.notes.ts, projects/canopy/src/lib/forms/toggle/toggle.stories.common.ts
Add a `focus` input to the form fields to allow for dynamic focusing.
This is particularly important when having to set the focus on a field that has an error so that screen reader users can amend the issue.
Storybook link: https://deploy-preview-218--legal-and-general-canopy.netlify.app/
=> feat(forms): add focus input to fields

projects/canopy/src/lib/brand-icon/brand-icon.component.spec.ts, projects/canopy/src/lib/brand-icon/brand-icon.component.ts
Ensures ids in brand icons are unique to comply with accessibility requirements
Fixes #226
The change can be validated on the brand icons component page using the Axe Dev Tools extension (in Chrome) which should no longer flag 'id attribute value must be unique'
Storybook link: https://deploy-preview-247--legal-and-general-canopy.netlify.app/?path=/story/components-brand-icon--standard
Screenshot:
=> fix(brand-icons): ensure ids are unique

projects/canopy/src/lib/brand-icon/brand-icon.component.scss, projects/canopy/src/lib/brand-icon/brand-icon.component.spec.ts, projects/canopy/src/lib/brand-icon/brand-icon.component.ts, projects/canopy/src/lib/brand-icon/brand-icon.notes.ts, projects/canopy/src/lib/brand-icon/brand-icons.stories.ts
This PR fixes and issue where the global colour for the brand icon was not applied anymore.
It also fixes an issue where it was not possible to set the specific colour for a single item.
@andy-polhill @paul-request I'm wondering if this should be flagged as breaking change. Paul, you will have to update your brand icon to pass the specific colour to it.
Fixes #251
The colour for the brand icons should be have the functionality to be applied both globally and specifically.
Storybook link: https://deploy-preview-252--legal-and-general-canopy.netlify.app/?path=/story/components-brand-icon--standard
Screenshot (first item is using the colour input):
=> Updates to brand icons colours

projects/canopy/src/lib/data-point/data-point/data-point.component.scss
In IE11, `flex: 1` is internally treated as `flex: 1 1 0px` instead of `flex: 1 1 0` like other browsers which causes items to mis-align, as that means the item has a width of 0px rather than the width of it's content:
=> fix(data-point): layout issue in IE11 with flex shorthand

projects/canopy/src/lib/data-point/data-point/data-point.component.scss
My previous fix to change `flex: 1` to `flex: 1 1 0` worked when updating in dev tools, but when loaded  via the stylesheet it does not work as `flex-basis: 0` is treated an an invalid value as it requires a unit (like px, for example). So changing it to `auto` fixes the layout for IE11.
I suspect `flex-basis: auto` is what we wanted anyway, so that the datapoint have equal width.
=> fix(data-point): fix IE11 data point layout issue

projects/canopy/src/styles/mixins.scss
Update the `lg-breakpoint` mixin to remove `1px` from the `max-width` breakpoint so that there is no overlap between min and max width media queries.
Behaving before the change:
https://user-images.githubusercontent.com/8397116/114399098-767a6880-9b98-11eb-9a87-1a5553ff1be8.mov
Behaviour after the change:
https://user-images.githubusercontent.com/8397116/114399124-7da17680-9b98-11eb-9295-29a9ba52bfae.mov
=> fix(grid): update lg-breakpoint mixin

projects/canopy/src/lib/alert/alert.component.scss, projects/canopy/src/lib/details/details.component.scss, projects/canopy/src/lib/forms/validation/validation.component.scss
Add back the margin to the alert icon (removed by mistake https://github.com/Legal-and-General/canopy/commit/3f0e52c800e7f53e011fdc245b80653b47fd0094) and fixes the breaking change introduced in `5.8.0` where a new `variants.scss` was introduced which requires adding the import in every project using `scss` files. For the moment we will import the file in each component that uses it but flagged as deprecated. The breaking change will be addressed in the `next` branch.
Storybook link: https://deploy-preview-314--legal-and-general-canopy.netlify.app/
=> Fix some issues with the alert and the variants

.releaserc, projects/canopy/src/lib/alert/alert.component.scss, projects/canopy/src/lib/details/details.component.scss, projects/canopy/src/lib/forms/validation/validation.component.scss, projects/canopy/src/styles/mixins.scss
This PR updates the `next` branch with the latest master and in particular the last commit (8e86ab4) reverts the following commits:
- 86c2d774ffd39ab967c0f532532adfd630ce4447
- fb5c03ed204e2ca48d48e65bb71f1ec454ce9e6c
- 5f6f4b54b39611143caef1b4ae8fcfd7d46af291
BREAKING CHANGE: The following change removes the variants imports
from the alert, details and validation components.
If using the global scss modules, update your main scss file to
import `canopy/styles/variants`.
=> Next: revert variants imports

projects/canopy/src/styles/mixins.scss
The variant styling for `.lg-btn--outline-primary` is missing in `next`, this adds them back in.
Storybook link: https://deploy-preview-333--legal-and-general-canopy.netlify.app/?path=/story/directives--variant
Design link: n/a
Screenshot: 
**Before**
**After**
=> fix(variants): add outline primary button override

projects/canopy/src/lib/button/button.stories.ts, projects/canopy/src/styles/mixins.scss
~Th `lg-link` mixin used `!important` to apply colours to links inside
one of the `lg-variant` classes (such as info, success, error, etc).
However, this caused issues with the `lg-button` directive when used to
style a link as a button, because the global link styles use `lg-link`.
This is fixed by making `!important` an opt in paramter of the `lg-link`
mixin, so that the variant styles can still use it and apply `!important`,
but that won't affect any other uses of the `lg-link` mixin.~
**Edit:**
Following the discussion on the use of `!important` for the links inside `lg-variant`, we have decided to remove `!important` completely from the `lg-link` mixin.
This change also edits the button story, so that it displays both a normal button and a link styled as a button (separate commit). …
=> fix(button): ensure link styles don't override a link styled as button

projects/canopy/src/lib/variant/variant.stories.ts, projects/canopy/src/styles/mixins.scss
The `lg-link` mixin is used to style links inside the variant CSS (e.g. for success, error
variants). However it was causing layout issues as it was clashing with the `.lg-btn` styles. This
is because the links inside varaint CSS were gaining higher specifity. Adding `a:not(.lg-btn)`
prevents this from happening.
**Before**
**After**
=> fix(variants): prevent lg-link from overiding lg-btn styles

projects/canopy/src/lib/hero/hero-card-title/hero-card-title.component.scss
The Hero Card Title component relied on passing a class to the `lg-heading` component. This input was
recently removed, causing this styling to break. This change adopts the same approach as
`lg-accordion` whereby the headings are styled directly.
**Before**
**After**
=> fix(hero): fix broken styling on hero card title

projects/canopy/src/lib/variant/variant.stories.ts, projects/canopy/src/styles/mixins.scss
Add styles for hover and active state, to variant buttons.
Note FYI: After a discussion with Michelle from the design team, we decided on this temporary solution until we design and build the component that combines the current Alert component, theDetail component, the Form Validation component and the Variant Directive that is being modified here. Inside variants we may only use the outline-primary button.
Implementation for pre-release branch( next ): [PR here](https://github.com/Legal-and-General/canopy/pull/350)
Design link: [design link](https://legalandgeneral.invisionapp.com/console/share/SB10JVR247UQ/613975239/play)
=> fix(variants): add hover and active state style to variant buttons

package-lock.json, package.json, projects/canopy/src/styles/variables/_colors.scss
Bumps stylelint to 13.13.1 and also removes a duplicate variable which showed up after running the
updated version of stylelint
=> build(deps-dev): bump stylelint from 13.12.0 to 13.13.1

projects/canopy/src/styles/mixins.scss
Add ability to apply the expressive font when using the _@lg-font-size_ mixin by enhancing the mixin with the third parameter _type_ with the default value null. When no parameter provided for the type of font family there will be no overriding of the font family set from another class. If we provide _productive_ as the value for the type parameter it will override the font family with the productive (Roboto) font. If the _expressive_ value has been set as a type parameter, expressive (Lyon) font will be set.
Fixes #224 
No requirements are needed. If we don't provide type parameter to the lg-font-size mixin there will be no changes to the font-family. …
=> feat(scss): add font type parameter to lg-font-size mixin

.github/dependabot.yml
As suggested in [this Dependabot PR](https://github.com/Legal-and-General/canopy/pull/366), this change should disable all Dependabot updates for Angular packages, as we do these manually at the same time.
Shout if you don't think this is the right thing to do.
=> build(dependabot): ignore all angular updates

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/canopy.module.ts, projects/canopy/src/lib/carousel/carousel-item/carousel-item.component.html, projects/canopy/src/lib/carousel/carousel-item/carousel-item.component.scss, projects/canopy/src/lib/carousel/carousel-item/carousel-item.component.spec.ts, projects/canopy/src/lib/carousel/carousel-item/carousel-item.component.ts, projects/canopy/src/lib/carousel/carousel.component.html, projects/canopy/src/lib/carousel/carousel.component.scss, projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.ts, projects/canopy/src/lib/carousel/carousel.module.ts, projects/canopy/src/lib/carousel/carousel.notes.ts, projects/canopy/src/lib/carousel/carousel.stories.ts, projects/canopy/src/lib/carousel/index.ts, projects/canopy/src/public-api.ts, projects/canopy/src/styles/variables.scss, projects/canopy/src/styles/variables/components/_carousel.scss
This PR adds a new carousel component which will be used on OSS.  This MVP version currently only supports click / keyboard navigation.  Swipe gesture and autoplay support to be added in future sprints.
View on [Netlify](https://deploy-preview-386--legal-and-general-canopy.netlify.app/?path=/story/components-carousel--standard)
=> feat: carousel component added

projects/canopy/src/lib/side-nav/side-nav.component.scss
Fixes an issue where global link styling was affecting the side nav links
=> fix(side-nav): remove global link styling from side nav links

projects/canopy/src/styles/mixins.scss
The `.lg-unstyled-link` class is used for turning off the global Canopy link styling, but the focus
state was still getting the focus colour of white.
Add the `.lg-unstyled-link` class to a link and apply `:focus`.
**Before**
**After**
=> fix(links): remove white text on focus with .lg-unstyled-link

projects/canopy/src/styles/mixins.scss
The visually-hidden styles can be overridden if the element has another class applied to it. For example, an input's label has `width: 100%` which overrides visually hidden's 1px width on mobile, which was breaking my layout. Given the nature of the visually-hidden class, I feel all of its values should be `!important`.
=> fix(utils): dont allow override of visually hidden styles

projects/canopy/src/lib/data-point/data-point-label/data-point-label.component.html, projects/canopy/src/lib/data-point/data-point-label/data-point-label.component.scss
Fixes issue where data point headings had the incorrect styling.
Screenshot:
Before:
After:
=> fix(data-point): incorrect heading styles

docs/USAGE.md, projects/canopy/src/styles/typography.scss
409
The current settings in typography.scss assume a directory structure that some projects do not have (i.e. /assets/fonts). This causes webpack builds to fail as it is difficult/impossible to store the Lyon fonts in a location that can be found.
Fixes #409
=> fix(typography): enable lyon font path setting

projects/canopy/src/lib/forms/sort-code/sort-code.component.spec.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.ts, projects/canopy/src/lib/forms/sort-code/sort-code.notes.ts, projects/canopy/src/lib/forms/validation/form.stories.ts
This PR fixes an issue where the sort code form field was not returning any specific error if any of the inputs where triggering the `required` error. Now the error returned is `requiredField` so that validation can be customised a bit more. 
Being able to return a different error message when the field is required.
=> fix(sort-code): update logic to return requiredField

projects/canopy/src/lib/button/button-group/button-group.component.scss
The margin button shouldn't be necessary as the buttons are usually always at the bottom of a page.
Before:
After:
=> fix(button-group): remove margin bottom

projects/canopy/src/lib/card/card.stories.ts, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.scss, projects/canopy/src/styles/mixins.scss
- Update details heading incorrect font size, caused by removal of the input class on `lg-heading`
- Update style of `:visited:hover` link
**Details Screenshot**
Before
After
**Link screenshot**
Before
After
=> Fix details heading and link style

projects/canopy/src/lib/table/table-cell/table-cell.component.html, projects/canopy/src/lib/table/table-cell/table-cell.component.scss, projects/canopy/src/lib/table/table-cell/table-cell.component.spec.ts, projects/canopy/src/lib/table/table-cell/table-cell.component.ts, projects/canopy/src/lib/table/table.notes.ts, projects/canopy/src/lib/table/table.stories.ts, projects/canopy/src/lib/table/table/table.component.scss, projects/canopy/src/lib/table/table/table.component.spec.ts
Adds new option to `lg-table-cell` called `stackSm`. If set, this option will stack the labels on top of the cell content, instead of side by side. E.g. 
```
<td lg-table-cell [stackSm]="true">
```
Also introduces a border to the top of the table.
A new story component is added to render a table with a large amount of copy in each cell, to catch these designs: https://legalandgeneral.invisionapp.com/console/share/JKZ6TDGSC4G/597020691/inspect
~Note this is still draft, will need to update notes and unit tests once the general approach is approved.~
Ready for full review 🙂 
----
Design link: https://legalandgeneral.invisionapp.com/console/share/JKZ6TDGSC4G/597020691/inspect
=> feat(table): add stackedOnMobile option and long copy version of table

projects/canopy/src/styles/grid.scss, projects/canopy/src/styles/grid.stories.ts
Ports over various grid classes from the original http://flexboxgrid.com/ styles. Allows ordering and alignment at different viewport sizes.
=> feat(grid): add breakpoint-specific alignment and order classes

projects/canopy/src/styles/links.notes.ts, projects/canopy/src/styles/links.stories.ts, projects/canopy/src/styles/mixins.scss
Fix an issue where the inline block links had different line height than the inline ones.
Also the inline block links on hover were causing the below content to shift.
Behaviour before:
https://user-images.githubusercontent.com/8397116/124100493-6e72ec00-da56-11eb-9f1a-cbdb6278f703.mov
Behaviour after:
https://user-images.githubusercontent.com/8397116/124100090-0fad7280-da56-11eb-9638-3598df791685.mov
Storybook link: https://deploy-preview-442--legal-and-general-canopy.netlify.app/?path=/story/links--utils
=> fix(links): update line height for the links

projects/canopy/src/lib/side-nav/side-nav-bar-item-content/side-nav-bar-item-content.component.scss, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.scss, projects/canopy/src/lib/side-nav/side-nav.component.scss, projects/canopy/src/styles/variables/components/_side-nav.scss
The recent work to update the Canopy links caused some unwanted visited styles on the side nav. This PR fixes those to make them the desired states.
=> fix(side-nav): override side nav visited link styles

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/button/button.component.scss, projects/canopy/src/lib/button/button.interface.ts, projects/canopy/src/lib/button/button.notes.ts, projects/canopy/src/lib/button/button.stories.ts, projects/canopy/src/lib/forms/input/input.stories.ts, projects/canopy/src/lib/promo-card/promo-card.notes.ts, projects/canopy/src/lib/promo-card/promo-card.stories.ts, projects/canopy/src/styles/variables/components/button/_button-solid.scss
This recreates the original PR by @Patil2099 (https://github.com/Legal-and-General/canopy/pull/451), to remove the `solid-secondary` button variant.
BREAKING CHANGE: removed the `solid-secondary` button variant. Use the `solid-primary` or any other button variant instead.
fix: #450
=> feat(buttons): remove solid-secondary button

projects/canopy/src/styles/mixins.scss
Unstyled links still inherited the global link hover color and background, which need to be reset to avoid undesirable behaviour on hover.
- [x The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
=> fix(links): reset color and background of unstyled link on hover

projects/canopy/src/lib/quick-action/quick-action.component.scss, projects/canopy/src/styles/variables/components/_quick-action.scss
fix #469
Update quick action background to white to ensure the text is still visible against varying backgrounds
Fixes #469 
Ensure the text on the quick actions is visible against all backgrounds (storybook allows the background colour to be changed)
Storybook link: https://deploy-preview-470--legal-and-general-canopy.netlify.app/?path=/story/components-quick-action--link
https://deploy-preview-470--legal-and-general-canopy.netlify.app/?path=/story/components-quick-action--button
Screenshot:
=> fix(quick-action): set background to white

projects/canopy/src/lib/forms/sort-code/sort-code.component.scss
The sort code fields are slightly larger than they should be.  This change addresses that.
#483
Please note that the original size of the sort code input fields was originally intended to be about 60px.  However, through padding and other css it ended up being about 55px.  The update from #464 forced the input to resize correctly, which has led to this discrepancy.  The width for the individual sort code input boxes has been set to 55px (3.4375rem), rather than the original 60px (3.75rem).  
Netlify link: https://deploy-preview-484--legal-and-general-canopy.netlify.app/?path=/story/components-form-sort-code--standard
=> fix(sort-code): changes the size of the sort code fields

projects/canopy/src/lib/modal/modal-body-timer/modal-body-timer.component.html, projects/canopy/src/lib/modal/modal-body-timer/modal-body-timer.component.spec.ts, projects/canopy/src/lib/modal/modal-body-timer/modal-body-timer.component.ts, projects/canopy/src/lib/modal/modal.notes.ts, projects/canopy/src/lib/modal/modal.stories.ts
Takes the input of the timer in seconds and converts it to a minutes/seconds format e.g. from 90 to "1:30"
=> feat(modal): format timer input

.github/actions/gh-pages-storybook/README.md, .github/actions/gh-pages-storybook/action.yml, .github/actions/gh-pages-storybook/index.js, .github/actions/gh-pages-storybook/package-lock.json, .github/actions/gh-pages-storybook/package.json, .github/workflows/pages_deploy.yml
This PR will enable deployment of the master branch to GitHub pages. It works by executing the necessary commands to run the storybook static build and commit them to the gh-pages branch.
I decided to roll this manually as we have been wary of using actions from unknown sources, at least for the time being. We could fork an action and host it within our org but this would require quite a lot of extra work
There are some hopefully workable compromises.
1. The commit message in the gh-pages branch does not have the latest release version. This can be determined using Git but I was hoping to get this part working first.  
2. The default token doesn't have the ability to setup Github Pages, it can commit to the branch, but can't create the static site. This will have to be done manually.
3. …
=> GitHub pages deploy

projects/canopy/src/lib/tabs/tab-nav-content/tab-nav-content.component.spec.ts, projects/canopy/src/lib/tabs/tab-nav-content/tab-nav-content.component.ts
add missing role to tab-nav-content element and get rid of the AxE accessibility issue by doing that
AxE was flagging ARIA accessibility issue for the tab content. The fix was to add a role of `tabpanel` to it.
Screenshot:
=> fix(tab-nav-bar): fix AxE Aria accessibility issue

projects/canopy/src/lib/page/page.component.html, projects/canopy/src/lib/page/page.component.ts
It has been raised by both the Axe tool and by our external accessibility partner that the skip link
need to have an id reference. This PR adds that to the skip link.
Fixes #508
=> fix(page): add href to skip link

projects/canopy/src/lib/page/page.component.scss
Adding an explicit bg color of white ensures that there is sufficient contrast when implmeented by
consuming apps with background colors other than white
Fixes #431
=> fix(page): fix contrast issue with skip link

docs/USAGE.md
I noticed we didn't link to the breaking change docs from the usage guide. I created the link and updated a few extra details.
=> docs(usage): improves breaking change docs

.github/actions/gh-pages-storybook/index.js
This should be the last tweak the get the GitHub pages deploy working.
=> docs(gh-pages): corrects path for git add

netlify.toml
Redirects the master branch deployment from netlify to GitHub pages.
=> docs(netlify): redirects master deployment to GitHub pages

projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.scss
Remove the `display: flex` from the chevron icon on the right of the details component as it was causing an issue with the size of the icon itself.
Before:
After:
=> fix(details): remove flex from the status icon

projects/canopy/src/lib/footer/footer.component.html, projects/canopy/src/lib/footer/footer.component.spec.ts, projects/canopy/src/lib/footer/footer.component.ts, projects/canopy/src/lib/footer/footer.model.ts, projects/canopy/src/lib/footer/footer.notes.ts, projects/canopy/src/lib/footer/footer.stories.ts
Updated the footer inputs for primary and secondary links, so that they can accept and render an ID
value
=> feat(footer): include ID in footer link model

projects/canopy/src/lib/footer/index.ts, projects/canopy/src/lib/page/page.component.scss, projects/canopy/src/styles/variables/_main.scss
This PR adds the z-order for `skip to main content` link also export the footer model.
=> Export link model and set z order for skip link

projects/canopy/src/lib/primary-message/primary-message-title/primary-message-title.component.scss
This fixes the issue when using a heading within the title of the `primary-message` component where the styles of the title where not applied.
=> fix(primary-message): add style for when a heading is used

projects/canopy/src/lib/page/page.component.scss
On a low resolution device zoomed at 200%, page content scrolls horizontally. Setting the max-width
to 100vw solves this issue.
This was raised as an issue by our accessibility testers.
=> fix(page): add max width to page to fix page scrolling at 200% zoom

projects/canopy/src/styles/variables/components/button/_button-outline.scss
The hover state colour of the `outline-primary` button was flagged by DIG as inaccessible.
This is a temporary solution (suggested by James) while the designers review all the buttons styles.
=> fix(buttons): update hover state of outline-primary

.github/workflows/master_push.yml
Latest push to master after the update to Semantic Release failed on `release` because now Node 14 is a requirement. 
This updates the job to run on Node v14.
=> ci(master-push): use Node version 14 on release job

projects/canopy/src/lib/alert/alert.component.spec.ts, projects/canopy/src/lib/alert/alert.component.ts, projects/canopy/src/lib/alert/alert.stories.ts, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.ts, projects/canopy/src/lib/details/details.component.spec.ts, projects/canopy/src/lib/details/details.component.ts, projects/canopy/src/lib/details/details.stories.ts, projects/canopy/src/lib/forms/validation/validation.component.spec.ts, projects/canopy/src/lib/forms/validation/validation.component.ts, projects/canopy/src/lib/variant/variant.directive.spec.ts, projects/canopy/src/lib/variant/variant.interface.ts
After discussion, we have agreed t revert the use of enums for CSF stories. This PR reverts the ones created thus far.
=> fix(enums): revert enums back to types for CSF stories

.storybook/main.js, documentation.json, projects/canopy/src/lib/brand-icon/brand-icon.notes.ts, projects/canopy/src/lib/brand-icon/brand-icons.stories.ts
Upgrades the Brand Icon to CSF format. Makes the brand icon story work in Storybook v6.
=> feat(brand-icon): upgrade to CSF format

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/forms/input/input-field.component.scss, projects/canopy/src/lib/forms/sort-code/index.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.ts, projects/canopy/src/lib/forms/sort-code/sort-code.directive.spec.ts, projects/canopy/src/lib/forms/sort-code/sort-code.directive.ts, projects/canopy/src/lib/forms/sort-code/sort-code.module.ts, projects/canopy/src/lib/forms/sort-code/sort-code.notes.ts, projects/canopy/src/lib/forms/sort-code/sort-code.stories.ts, projects/canopy/src/lib/forms/validation/form.stories.ts, projects/canopy/src/styles/variables/_variants.scss
This PR implements the sort code as a single field via a new directive.
The component is still available but will be deprecated in the next major release.
=> Single field sort code

projects/canopy/src/lib/forms/sort-code/sort-code.directive.spec.ts, projects/canopy/src/lib/forms/sort-code/sort-code.directive.ts
Updated the size of the input based on new design.
Before:
After:
=> Update size attribute for sortcode

package-lock.json, package.json
Version `0.1102.15` of `@angular-devkit/build-angular` was causing an issue where storybook wouldn't start with the following error:
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin autoprefixer requires PostCSS 8.
```
even though in the `package.json` we specifically install `postcss` at version 8.
After some googling I found this stackoverflow: https://stackoverflow.com/questions/64925926/error-postcss-plugin-tailwindcss-requires-postcss-8
and realised that `tailwindcss` is actually used by the angular devkit. Rolling back the version seem to fix the issue.
=> Rollback version of angular devkit causing the storybook to not load

projects/canopy/src/lib/table/table-head-cell/table-head-cell.component.spec.ts, projects/canopy/src/lib/table/table-head-cell/table-head-cell.component.ts
Update the code to use `style.text-align` which fixes the error logged by the `w3 html validator`:
```
The align attribute on the th element is obsolete. Use CSS instead.
```
https://user-images.githubusercontent.com/8397116/147654033-1dea9dad-8604-4850-9f9a-e76a7072fcdb.mov
=> fix(table): remove align attribute from html

projects/canopy/src/lib/forms/radio/radio-button.component.html, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio.stories.ts
This PR: 
- adds an extra content projection element `<ng-content select="lg-hint">` so that we're able to add text below the radio button for the cases where design dictates so.
Check the PS below:
=> Add extra content projection inside the radio buttons

projects/canopy/src/lib/modal/modal.component.html, projects/canopy/src/lib/modal/modal.component.ts
Update code to use the `mousedown` event instead of the `click` so that if a user clicks inside the modal and
drags the mouse on the overlay the modal doesn't close.
Fixes #666
=> fix(modal): update event to close on overlay click

projects/canopy/src/lib/footer/footer.component.html, projects/canopy/src/lib/footer/footer.component.scss, projects/canopy/src/lib/footer/footer.component.spec.ts, projects/canopy/src/lib/footer/footer.component.ts, projects/canopy/src/lib/footer/footer.interface.ts, projects/canopy/src/lib/footer/footer.notes.ts, projects/canopy/src/lib/footer/footer.stories.ts, projects/canopy/src/lib/footer/index.ts, projects/canopy/src/lib/header/header.component.html, projects/canopy/src/lib/modal/modal.module.ts, projects/canopy/src/styles/variables/components/_footer.scss
Update the footer so that it can be co-branded.
Also add the option to have buttons in the secondary links. This is for scenarios where a user has to add the cookie preference functionality. 
In addition to that the interface for the secondary link now allows a `class` field because in our specific case the cookie popup doesn't work unless there is both the `id` and the `class` specified on the element.
Also rename `footer.model.ts` to be `footer.interface.ts` for consistency.
https://user-images.githubusercontent.com/8397116/148810911-fb56bbe5-0dc9-4f51-971b-161126bc6f75.mov
=> Add option to co-brand the footer

projects/canopy/src/styles/mixins.scss
This commit fixes a bug where if a link was focused. and hovered at the same time the focus outline would disappear.
I have tested around and the change doesn't seem to affect anything.
Before and after video:
https://user-images.githubusercontent.com/8397116/149113191-03a121e2-27f6-43b8-a0e3-7010c530eae5.mov
=> fix(links): update focus hover style

projects/canopy/src/lib/forms/radio/radio-button.component.scss
This PR: 
- adjusts the padding on the text content to properly align with the label text (radio button)
=> fix(radio-button): adjust text padding to align with label

projects/canopy/src/lib/footer/footer.component.scss, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.stories.ts, projects/canopy/src/lib/forms/checkbox-group/filter-group.stories.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/forms/radio/radio-button.component.html, projects/canopy/src/lib/forms/radio/radio-button.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/forms/radio/radio.stories.ts, projects/canopy/src/lib/forms/radio/segment.stories.ts, projects/canopy/src/lib/forms/toggle/toggle.component.html, projects/canopy/src/lib/forms/toggle/toggle.component.spec.ts, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/toggle/toggle.notes.ts, projects/canopy/src/lib/forms/toggle/toggle.stories.common.ts, projects/canopy/src/styles/mixins.scss
This PR:
- reverts the commit with a "fix" for the focused hover state (this actually broke the state for some other links)
- adds specific focused hover state to the footer links
- add a blur output to the radios and toggles
https://user-images.githubusercontent.com/8397116/149518393-d36991b7-8c4b-46de-a3ab-dfaf1bdf5a15.mov
https://user-images.githubusercontent.com/8397116/149518435-08558684-17c8-424e-88bf-b8aac86a0548.mov
https://user-images.githubusercontent.com/8397116/149518464-15fc423c-3369-47e3-81b3-c02980e8dbb9.mov
=> Add blur output to radios and toggles

projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.ts, projects/canopy/src/lib/carousel/carousel.notes.ts, projects/canopy/src/lib/carousel/carousel.stories.ts
Stop carousel when any button inside carousel item has been clicked and fix broken view on tab
switch
If a CTA on one of the advertising tiles has focus, and the animation / scrolling is on, it breaks.
Tabbing between the controls on the ads DCI-17572
Fixes #622
=> fix(carousel): carousel scroll behaviour when interacted with cta

projects/canopy/src/lib/carousel/auto-play/auto-play.component.scss, projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.ts
keyboard focus carousel fix
Stop carousel when any button inside carousel item has been clicked and fix broken view on tab
switch
If a CTA on one of the advertising tiles has focus, and the animation / scrolling is on, it breaks.
Tabbing between the controls on the ads DCI-17572
selectedItemIndexSet set to BehaviourSubject so that selectedItemIndexSet$ be exposed by targeting the Carousel with ViewChild decorators.
Advertising Carousel scroll behaviour when CTA is interacted with or has focus.
DCI-18540, DCI-17572
=> fix(carousel): carousel focus fix

projects/canopy/src/lib/footer/footer.component.html, projects/canopy/src/lib/footer/footer.component.spec.ts, projects/canopy/src/lib/footer/footer.component.ts, projects/canopy/src/lib/footer/footer.notes.ts, projects/canopy/src/lib/footer/footer.stories.ts, projects/canopy/src/lib/header/header.component.html, projects/canopy/src/lib/header/header.component.spec.ts, projects/canopy/src/lib/header/header.component.ts, projects/canopy/src/lib/header/header.notes.ts, projects/canopy/src/lib/header/header.stories.ts
Header and footer:
BREAKING CHANGE: the input for the second logo has been changed from `secondLogo` to `secondaryLogo` to be inline with the inputs `primaryLinks` and `secondaryLinks`.
Fix: #670
#315
=> Update input name for secondary logo in header and footer

projects/canopy/src/lib/carousel/auto-play/auto-play.component.ts
Fix accessibility bug for the carousel autoplay component in order for the screen reader not to loop the context of the carousel when we are in the page 
Fix: (carousel)-a11y loop context 
remove aria: polite attribute from the auto-play.component.html
=> fix(carousel): remove aria polite attribute 

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/tabs/tabs.component.html, projects/canopy/src/lib/tabs/tabs.component.spec.ts, projects/canopy/src/lib/tabs/tabs.component.ts, projects/canopy/src/lib/tabs/tabs.notes.ts, projects/canopy/src/lib/tabs/tabs.stories.ts
Fix accessibility bug described in issue #676. 
The team has decided to introduce a breaking change and remove the heading from the tab system
as unnecessary.
Fix: #676
=> fix(tabs): remove heading from tab component to fix a11y issue

projects/canopy/src/styles/grid.scss
One of the arguments of the percentage function was changed by mistake from  to 12. This reverts that change.
=> fix(grid): update wrong value in percentage

projects/canopy/src/lib/hero/hero-card-notification/hero-card-notification.component.html, projects/canopy/src/lib/hero/hero-card-notification/hero-card-notification.component.scss, projects/canopy/src/lib/hero/hero-header/hero-header.component.html, projects/canopy/src/lib/hero/hero-header/hero-header.component.scss, projects/canopy/src/styles/variables/components/_hero.scss
fix link not being clickable in the notification message, because of the overlay covering it
Because of the overlay, the link in the notification message could not be interacted with. The solution was to add ``pointer-events: none;``, transforming the overlay into a layer that should ignore / pass-through click-, tap-, scroll- and hover events.
Screenshot:
=> fix(hero-card-notification): fix link not clickable in notification

documentation.json, projects/canopy/src/lib/accordion/accordion.stories.ts, projects/canopy/src/lib/alert/alert.stories.ts, projects/canopy/src/lib/brand-icon/brand-icons.stories.ts, projects/canopy/src/lib/button/button-group/button-group.stories.ts, projects/canopy/src/lib/details/details.stories.ts, projects/canopy/src/lib/footer/footer.stories.ts, projects/canopy/src/lib/forms/checkbox-group/filter-group.stories.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/header/header.stories.ts, projects/canopy/src/lib/heading/heading.stories.ts, projects/canopy/src/lib/icon/icons.stories.ts, projects/canopy/src/lib/modal/modal.stories.ts, projects/canopy/src/lib/primary-message/primary-message.stories.ts, projects/canopy/src/lib/separator/separator.stories.ts, projects/canopy/src/lib/spinner/spinner.stories.ts
I have renamed single stories to remove the redundant expandable menu items
=> Remove "Standard" naming convention for single stories

projects/canopy/src/lib/details/details.component.html
- issues that were flagged by the accessibility tools (axe devtools) related to the `aria-labelledby` attribute which requires a `role` attribute as well on `div` tags
See the two screenshots (before & after the fix). Please note that the errors that are shown in the "after fix" image are related to local Gramarly extension so they're not related to the project.
=> Fix(details): add role attribute for accessibility 

package.json
Remove `syntax` parameter from `pre-commit` hook as deprecated and blocking new commits.
The syntax is now specified in the `.stylelintrc`.
=> fix(stylelint): remove syntax param from pre-commit

.github/dependabot.yml, .github/workflow-scripts/combine-dependabot-prs.js, .github/workflows/codeql_analysis.yml, .github/workflows/dependabot.adhoc.yml, .github/workflows/dependabot.scheduled.yml, .github/workflows/pull_request.yml
This PR:
- Adds a scheduled and ad-hoc workflow for batching Dependabot PRs
- This will fetch all Dependabot PRs that are open, adding their commits into a combined PR branch (which is created if it doesn't exist)
- This means that manually combining dependency updates is a thing of the past
- ...and will save everyone a lot of time :)
- Changes the dependabot config to auto-rebase its PRs
- Removes the Dependabot section of the PR template
How this works in practice:
- Every Monday and Wednesday morning the scheduled workflow combines any open Dependabot PRs into one
- The combined PR runs the full checks as per any other PR
- Approve and merge
NB: If there are conflicts (which happens if two adjacent dependencies in `package.json` have updates), just merge the combined PR, then run the …
=> Add actions to combine dependabot PRs into one

.stylelintrc, projects/canopy/src/styles/grid.scss
When using the `grid` the projects build fails with:
```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $number: calc(1 / 12) is not a number.
╷
154 │     $width: percentage(calc($i / 12));
```
`calc()` doesn't seem to work within `percentage()`.
I have now run the `sass-migration` package and `calc` has been updated to `math.div`.
https://user-images.githubusercontent.com/8397116/160409651-04eb1769-ad43-40dd-bfdb-222088437c2e.mov
=> fix(grid): replace calc with math.div for division

projects/canopy/src/lib/forms/radio/radio-group.component.ts
The stack input for the segment component was not working when added to an application (worked on Storybook).
This has now been fixed (tested within an application):
https://user-images.githubusercontent.com/8397116/160885436-47298e6a-9900-4c23-adac-88fff17ebef7.mov
=> fix(segment): stack input is now set correctly

projects/canopy/src/lib/canopy.module.ts, projects/canopy/src/lib/canopy.service.ts
Add deprecation message to Canopy module and service.
The removal of the Canopy module was discussed here: https://github.com/Legal-and-General/canopy/discussions/768
The service is empty and unused - deprecating it just to be 100% sure before the next breaking change release.
=> docs(canopy): add deprecation message to Canopy module and service

.storybook/preview-head.html
Storybook was overriding the super-blue colour of the links in the intro page making them inaccessible.
Before:
After:
=> docs(storybook): update link colour

.github/workflow-scripts/gh-pages/create-gh-deployment.js, .github/workflow-scripts/gh-pages/deploy.js, .github/workflows/branch_pages_deploy.yml
Remove environment logic as it is unnecessary to create a different environment for each branch.
I have set the environment to the one GitHub pages already uses.
Workflow test run that replicates `master`: https://github.com/Legal-and-General/canopy/runs/6420417310
Workflow to deploy this environment: https://github.com/Legal-and-General/canopy/actions/runs/2318593788
Tested deployment status update using the `job.status` here: https://github.com/Legal-and-General/canopy/runs/6469799176?check_suite_focus=true
=> docs(gh-pages): fix environment issue with deployment

.eslintrc.js, projects/canopy/src/lib/heading/heading.component.scss, projects/canopy/src/lib/heading/heading.component.spec.ts, projects/canopy/src/lib/heading/heading.component.ts
This change fixes a bug where the spacing applied via the LgPadding or LgMargin directives was not applied.
In addition to that allows for static attributes to be added to the component host metadata (https://netbasal.com/adding-static-attributes-to-the-host-element-in-angular-b16cd33b424e).
Fixes #171
Relates to #698
https://user-images.githubusercontent.com/8397116/172418914-5fb35ee4-fe83-4242-ae60-f496cd0ed127.mov
A user should be allowed to add spacing to the `lg-heading` component via the LgPadding and LgMargin directives.
=> Fix bug with spacing not applied to lg-heading component

projects/canopy/src/styles/variables/_colors.scss
Add new RGB colour variables:
```
--color-leafy-green-rgb: 2, 136, 68;
--color-dandelion-yellow-rgb: 255, 213, 0;
--color-charcoal-rgb: 51, 51, 51;
```
`--color-super-blue-rgb: 0, 118, 214;` was already present.
Discussion available here: https://github.com/Legal-and-General/canopy/discussions/913
=> style(colours): add new RGB colour variables

projects/canopy/src/lib/icon/icon.notes.ts
Update link to quote of `currentcolor` in the icon notes.
Fixes #927
=> docs(icon): update link to quote of currentcolor

projects/canopy/src/lib/variant/variant.notes.ts, projects/canopy/src/styles/mixins.scss
Update old leftover class within variant mixin to the new one so that the styles are applied correctly:
Before:
After:
Also fix small typo in documentation.
=> Fix button styles when within a variant

projects/canopy/src/lib/forms/radio/radio-group.component.scss
On a fieldset element the box shadow appears behind the legend element. Using the outline avoid the issues.
Fixes # ([issue](https://github.com/Legal-and-General/canopy/issues/925))
When the fieldset element is focused by Javascript this change means the border will look correct.
=> fix(radio-group): set fieldset focus via outline

projects/canopy/src/lib/breadcrumb/breadcrumb.stories.ts
Fix typo with the word `Annuity` in the breadcrumb component preview.
Before:
After:
=> docs(breadcrumb): update typo in component preview

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/pull_request.yml
Add commit lint to the CI so that we make sure people don't commit using `--no-verify`.
Also updates wrong links in issue template.
=> Add commitlint to CI

.github/workflows/pull_request.yml
Ignore `Lint commit` stage for the `dependency-updates` branch as message is automated.
=> ci(lint-commit): update workflow to skip check for dependabot-updates

.github/workflows/pull_request.yml, projects/canopy/src/lib/forms/radio/radio-button.component.html, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-button.component.ts, projects/canopy/src/lib/forms/radio/radio.interface.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/forms/radio/radio.stories.ts, projects/canopy/src/lib/forms/toggle/checkbox.stories.ts, projects/canopy/src/lib/forms/toggle/switch.stories.ts, projects/canopy/src/lib/forms/toggle/toggle.component.html, projects/canopy/src/lib/forms/toggle/toggle.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.spec.ts, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/toggle/toggle.interface.ts, projects/canopy/src/lib/forms/toggle/toggle.notes.ts, projects/canopy/src/lib/forms/toggle/toggle.stories.common.ts, projects/canopy/src/styles/variables/components/_radio.scss
Add `size` input to `radio` and `checkbox` inputs.
Also fixes an issue with the `commitlint` step in the CI not picking up the correct commits - caused by how GH checkout works.
Requirements discussed here: https://github.com/Legal-and-General/canopy/discussions/874
Radio `sm`:
Radio `lg`:
Checkbox `sm`:
Checkbox `lg`:
=> Add size input to radio and checkbox inputs

projects/canopy/src/lib/forms/radio/radio-button--segment.component.scss, projects/canopy/src/styles/variables/components/_radio.scss
This PR adds a 'hover' state to the segment buttons/toggles and a 'pointer' as the cursor.
Designs: [designs](https://legalandgeneral.invisionapp.com/console/share/N4HBGD69TXC/597018576)
Screenshot:
=> fix(segment): add hover state

projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.html, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.ts, projects/canopy/src/lib/details/details.component.html, projects/canopy/src/lib/details/details.component.spec.ts, projects/canopy/src/lib/details/details.component.ts
I initially picked this ticket as I had noticed the attributes not being set correctly for the panel content in Storybook:
I could reproduce the issue locally so I refactored the code. It now works locally but Storybook seem to still have the issue.
I tested the component in one of our apps and both before and after I can see it working just fine so this is why I have marked this as refactoring instead of a fix.
No matter what I try Storybook seem to still have the issue so I believe this to be something to do with Storybook itself.
Related to: #726
=> refactor(details): update id and aria attributes

projects/canopy/src/lib/forms/checkbox-group/checkbox-group.stories.ts, projects/canopy/src/lib/forms/checkbox-group/filter-group.stories.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/forms/radio/segment.stories.ts
Fix a console error triggered on blur of certain form elements. This was raised by DIG Inclusion as Advisory and it only affects the Storybook site.
Updated components:
- checkbox group
- filter group
- filter
- segment
Before and after:
https://user-images.githubusercontent.com/8397116/187689533-427c8778-1abe-43e4-b51f-5e2888a21a94.mov
=> Fix console error triggered on blur of certain form elements

projects/canopy/src/lib/brand-icon/brand-icon.component.spec.ts, projects/canopy/src/lib/brand-icon/brand-icon.component.ts, projects/canopy/src/lib/brand-icon/brand-icon.notes.ts, projects/canopy/src/lib/brand-icon/brand-icons.stories.ts
Add inputs for setting the outlines and half tone colours of the brand icons
The brand icons outlines and half tone colours should be configurable so that they can be used on different backgrounds.
Environment: https://legal-and-general.github.io/canopy/sb-fep-824-brand-icons/?path=/story/components-brand-icon--standard-brand-icons
Screenshot:
=> Add inputs for setting the outlines and half tone colours of the brand icons

.storybook/main.js, projects/canopy/src/lib/spacing/index.ts, projects/canopy/src/lib/spacing/row-gap/index.ts, projects/canopy/src/lib/spacing/row-gap/row-gap.directive.spec.ts, projects/canopy/src/lib/spacing/row-gap/row-gap.directive.ts, projects/canopy/src/lib/spacing/row-gap/row-gap.module.ts, projects/canopy/src/lib/spacing/row-gap/row-gap.notes.ts, projects/canopy/src/lib/spacing/row-gap/row-gap.stories.ts, projects/canopy/src/lib/spacing/spacing.module.ts, projects/canopy/src/styles/grid.notes.ts, projects/canopy/src/styles/grid.stories.ts, projects/canopy/src/styles/spacing.scss
* enables consumers to use the `row-gap` CSS property using Canopy and it's spacing.
* accepts either a value or will default to `sm` row-gap.
* fixes a broken link in the storybook grid style docs.
Follows on from the discussion #1046.
**This draft PR is for master but I am open to it going into [@next](https://github.com/Legal-and-General/canopy/tree/next) if required.**
=> feat(lg-row-gap): adds new directive and classes

.storybook/main.js, projects/canopy/src/styles/blockquote.scss, projects/canopy/src/styles/blockquote.stories.mdx, projects/canopy/src/styles/blockquote.stories.ts, projects/canopy/src/styles/styles-classes.scss, projects/canopy/src/styles/variables/_main.scss
Add blockquote and cite global styles and documentation (the documentation will be enhances later on).
Screenshot:
=> Add blockquote styles and docs

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.module.ts, projects/canopy/src/lib/link-menu/docs/guide.stories.mdx, projects/canopy/src/lib/link-menu/docs/link-menu.stories.ts, projects/canopy/src/lib/link-menu/link-menu-item/link-menu-item.component.html, projects/canopy/src/lib/link-menu/link-menu-item/link-menu-item.component.spec.ts, projects/canopy/src/lib/link-menu/link-menu-item/link-menu-item.component.ts
* Now references the parent to determine what the target is and if it is "_blank" to then correctly add the 'opens in a new tab' text.
Fixes #1086
=> fix: link-menu-item so a11y text is set based on parent anchor target

projects/canopy/src/lib/header/header.component.scss, projects/canopy/src/lib/header/primary-navigation/primary-navigation.component.scss, projects/canopy/src/styles/variables/components/_header.scss
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1zd9hlQalpXYBY5YNoBPZTckVvvyj5pKA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=s_LWR77)
This fixes an issue where the header shadow was showing the page underneath on small devices.
Before:
After:
=> fix(header): update so that the shadow appears correctly on sm devices

projects/canopy/src/lib/header/account-menu/account-menu-list-item/account-menu-list-item.component.spec.ts, projects/canopy/src/lib/header/account-menu/account-menu-list-item/account-menu-list-item.component.ts, projects/canopy/src/lib/header/account-menu/account-menu.component.ts, projects/canopy/src/lib/header/header-logo/header-logo.component.html, projects/canopy/src/lib/header/header-logo/header-logo.component.spec.ts, projects/canopy/src/lib/header/header-logo/header-logo.component.ts, projects/canopy/src/lib/header/header.component.spec.ts, projects/canopy/src/lib/header/header.component.ts, projects/canopy/src/lib/header/primary-navigation/primary-navigation-list-item/primary-navigation-list-item.component.scss, projects/canopy/src/lib/header/primary-navigation/primary-navigation.component.html, projects/canopy/src/lib/header/primary-navigation/primary-navigation.component.scss, projects/canopy/src/styles/variables/components/_header.scss
1. Fixes the tab order across devices as the menus use flex box to place them in different orders on different devices and this was messing with the tab ordering, when going back and forth on sm devices.
2. Adds a transparent overlay over the page when the primary navigation is open.
=> feat(header): add overlay to primary nav and fix tab order

projects/canopy/src/lib/header/header.component.spec.ts, projects/canopy/src/lib/header/header.component.ts
Fixes an issue where account menu items were added after `ngOnContentInit`, so the item was incorrect and the focus was not set on the logo when shift + tabbing out of it. This fixes tat issue by subscribing to the changes on the querylist and and subscribing to the first item's `tabbedOut` output.
=> fix(header): handle tab out event for newly added account menu items

projects/canopy/src/lib/header/header-logo/header-logo.component.scss
Updates the header logo link to use the newer focus outline styles to match those used in the header navigation menus
=> fix(header-logo): update focus state to use new focus outline mixin

projects/canopy/src/lib/header/header.component.spec.ts, projects/canopy/src/lib/header/header.component.ts
This fixes an issue where a consumer hides/shows the navigation  but the burger menu does not re-appear. It now forces a re-render when primary navigation items change
=> fix(header): re-render menu toggle button when primary nav items change

projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.html, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.spec.ts, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.ts, projects/canopy/src/lib/card/card.module.ts, projects/canopy/src/lib/card/docs/card.stories.ts, projects/canopy/src/lib/card/docs/guide.stories.mdx, projects/canopy/src/lib/utils/external-links.spec.ts, projects/canopy/src/lib/utils/external-links.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1mGE4UESnBOdepcCGp60hDytvw5cx7T8A%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=N4Vbj6o)
This PR fixes a bug where internal links where causing an app to reload when using the `lg-card-navigation-title` (as described here: https://github.com/Legal-and-General/canopy/discussions/1169)
=> Update card navigation title to handle internal links

projects/canopy/src/lib/forms/date/date-field.component.html, projects/canopy/src/lib/forms/date/date-field.component.spec.ts
This PR fixes an issue with the `LgDateFieldComponent` where an empty duplicate label is generated. To fix this, I have removed the custom label and just used the default label generated by the `LgInputComponent` for each of the date inputs. This removes the need to specify custom ids as that will now be handled by the default behaviour in the children`LgInputComponent`s
=> fix(date-field): a11y issue with labels

projects/canopy/src/lib/card/card-content/card-content.component.ts
Have fixed the logic that applies the `lg-card-content--data-points` class to `lg-card-content` when `lg-data-point` is/are present in it. Previously the class was always being applied.
Fixes #1192
=> Fix card content styling

projects/canopy/src/lib/card/card-content-inner-data-points/card-content-inner-data-points.component.html, projects/canopy/src/lib/card/card-content-inner-data-points/card-content-inner-data-points.component.scss, projects/canopy/src/lib/card/card-content-inner-data-points/card-content-inner-data-points.component.spec.ts, projects/canopy/src/lib/card/card-content-inner-data-points/card-content-inner-data-points.component.ts, projects/canopy/src/lib/card/card-content/card-content.component.ts, projects/canopy/src/lib/card/card.module.ts, projects/canopy/src/lib/card/docs/card.stories.ts, projects/canopy/src/lib/card/docs/guide.stories.mdx, projects/canopy/src/lib/card/index.ts
This fixes more bugs with the data-points within the card content.
Having the styles within the card-content was breaking the layout of the card whenever there was more than just data-points in it. This PR adds a new component that wraps the styles specific to the data points so that they are not applied to everything else.
=> fix(card): move data points styles in card-content-inner-data-points

projects/canopy/src/lib/forms/input/docs/input.stories.ts, projects/canopy/src/lib/forms/input/input-field.component.scss, projects/canopy/src/lib/forms/select/select.scss
- Removes keyline padding and margin in the input field and select form that was introduced by changes to the focus on the 10.9.0 version. 
- Update storybook documentation for the input field to includes the prefix example.
Fixes #1200
=> Fixed input field un-focus on focus

projects/canopy/src/lib/card/docs/card.stories.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19X2p4vVe6exuqLxPzG7OZXYoUGOgFmCg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=z3l3fp7)
Removes top padding for lg-card-footer items that have lg-link-menu as first child
Fixes https://github.com/Legal-and-General/canopy/issues/1192
=> FEP-1772: remove top padding from card-footer story

.github/workflow-scripts/gh-pages/deploy.js, .github/workflow-scripts/gh-pages/download-branch-deploy-artifact.js, .github/workflow-scripts/gh-pages/get-pr-data.js, .github/workflows/branch_pages_deploy.yml, .github/workflows/pull_request.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18sUE1LaqFLvbY5AuTv1elGhuBAqh9k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=U-oXJ23)
The `sb-` prefix we use is now conflicting with the one from Storybook. In our scripts for `master` deployment we remove some of the folders with `sb-` as prefix and this now breaks the main environment as it removes some folder assets needed by Storybook to run ([`.github/workflow-scripts/gh-pages/deploy.js`](https://github.com/Legal-and-General/canopy/blob/master/.github/workflow-scripts/gh-pages/deploy.js#L153)). Our prefix is now more specific: `lg-sb-`.
=> ci(storybook): update prefix for folders to build in

projects/canopy/src/lib/header/docs/guide.stories.mdx, projects/canopy/src/lib/spinner/docs/guide.stories.mdx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1o1voV5AYvU1ZRVSDmaDq72VYSWD2q28%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=d2o8D5I)
This PR fix an issue with a missing import for the `Feedback` section on the Spinner guide and updates an incorrect output name for the Header docs.
=> Fixes to documentation

.storybook/main.js, .storybook/preview-head.html, projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.module.ts, projects/canopy/src/lib/card/card-content/card-content.component.scss, projects/canopy/src/lib/card/card-content/card-content.component.ts, projects/canopy/src/lib/list-with-icons/docs/guide.stories.mdx, projects/canopy/src/lib/list-with-icons/docs/list-with-icons.stories.ts, projects/canopy/src/lib/list-with-icons/index.ts, projects/canopy/src/lib/list-with-icons/list-with-icons-item/list-with-icons-item.component.html, projects/canopy/src/lib/list-with-icons/list-with-icons-item/list-with-icons-item.component.scss, projects/canopy/src/lib/list-with-icons/list-with-icons-item/list-with-icons-item.component.spec.ts, projects/canopy/src/lib/list-with-icons/list-with-icons-item/list-with-icons-item.component.ts, projects/canopy/src/lib/list-with-icons/list-with-icons.component.scss, projects/canopy/src/lib/list-with-icons/list-with-icons.component.spec.ts, projects/canopy/src/lib/list-with-icons/list-with-icons.component.ts, projects/canopy/src/lib/list-with-icons/list-with-icons.interface.ts, projects/canopy/src/lib/list-with-icons/list-with-icons.module.ts, projects/canopy/src/public-api.ts, projects/canopy/src/styles/blockquote.stories.mdx, projects/canopy/src/styles/variables/_variants.scss
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19jQfZ2NfSt8NkUjOgX8ULcSjzqJTx9EM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=64hDKqE)
Add new List with Icons component. 
In addition to this change, it updates any link within the `lg-card-content` to be black.
Create a list component that allows for icons to be added instead of bullets.
Design link: https://www.figma.com/file/hJUsMXF6fNJVoa57SJuMpX/Components?type=design&node-id=2-375&mode=dev
Screenshots:
=> Add List with Icons component

projects/canopy/src/lib/forms/date/date-field.component.ts, projects/canopy/src/lib/forms/date/docs/guide.stories.mdx, projects/canopy/src/lib/forms/validation/docs/form.stories.ts
This PR fixes a bug where the Date Field validation didn't work properly when used as part of a form group used in a child component. 
This was caused by the `@Host` decorator, which was taking into account only the direct `FormGroupDirective` of the parent component, it just worked if the date field was a direct child of the form where `[formGroup]` was defined.
=> Fix Date Field bug when used inside nested forms

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/card/card-subheading/card-subheading.component.html, projects/canopy/src/lib/card/card-subheading/card-subheading.component.scss, projects/canopy/src/lib/card/card-subheading/card-subheading.component.spec.ts, projects/canopy/src/lib/card/card-subheading/card-subheading.component.ts, projects/canopy/src/lib/card/card.module.ts, projects/canopy/src/lib/card/docs/card/card.stories.ts, projects/canopy/src/lib/card/docs/card/guide.stories.mdx, projects/canopy/src/lib/card/index.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX190HMfb0g6RHLFBjBzXVhWMnKyi3U3Rus%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=mEBJ-_-)
Add new `lg-card-subheading` component and update the lg-card docs.
Design link: https://www.figma.com/file/Mts4nibXQw6tDW2PTDHlKd/Patterns?node-id=212%3A2589&mode=dev
Screenshot:
=> FEP-1279: create a card subheading component

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/card/card-content/card-content.component.scss, projects/canopy/src/lib/card/card-content/card-content.component.ts, projects/canopy/src/lib/card/card-group/card-group.component.html, projects/canopy/src/lib/card/card-group/card-group.component.scss, projects/canopy/src/lib/card/card-group/card-group.component.spec.ts, projects/canopy/src/lib/card/card-group/card-group.component.ts, projects/canopy/src/lib/card/card.component.scss, projects/canopy/src/lib/card/card.module.ts, projects/canopy/src/lib/card/docs/card/card.stories.ts, projects/canopy/src/lib/card/docs/card/guide.stories.mdx, projects/canopy/src/lib/card/index.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1eYsB7JR7nrNWg2nvuJkSwWjtGkbLZDE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Bm2btjf)
Add a new `LgCardGroupComponent`: a container to group together two or more cards so that they are organised correctly throughout the different breakpoints and have the same height.
Grouping of cards is required for the new card navigation. It should also make the cards the same heights.
The above was also discussed here: https://github.com/Legal-and-General/canopy/discussions/1212#discussioncomment-6658606
Design links:
- https://www.figma.com/file/Mts4nibXQw6tDW2PTDHlKd/Patterns?type=design&node-id=524%3A6637&mode=design&t=7xP …
=> feat(card-group): add a new card group component

projects/canopy/src/lib/forms/radio/radio-button.component.scss
Fixes #827 
Sets the position of the radio button to absolute and adds fixed padding to prevent the radio button stretching when the label text goes over multiple lines
| Issue | Fix |
| --- | ---|
|<img width="80%" alt="image" src="https://github.com/Legal-and-General/canopy/assets/95081643/2169a0c1-6e7d-4d78-a6c1-10bfee74fd23">|<img width="80%" alt="image" src="https://github.com/Legal-and-General/canopy/assets/95081643/53c980d8-8390-41e1-8e11-dc995338d5bc">|
=> fix(radio-button): update position of toggle to account for longer labels

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/spinner/docs/guide.stories.mdx, projects/canopy/src/lib/spinner/docs/spinner.stories.ts, projects/canopy/src/lib/spinner/spinner.component.scss, projects/canopy/src/lib/spinner/spinner.component.spec.ts, projects/canopy/src/lib/spinner/spinner.component.ts, projects/canopy/src/lib/spinner/spinner.interface.ts, projects/canopy/src/styles/variables/components/_spinner.scss
This PR adds an **xs** size to the spinner component.
=> feat(spinner): add extra small size

projects/canopy/src/lib/table/table-cell/table-cell.component.scss
This PR fix the text alignment for the table content text.
Before:
After:
Fixes #1190 (https://github.com/Legal-and-General/canopy/issues/1190)
=> Fix table content alignment

projects/canopy/src/lib/alert/alert.component.spec.ts, projects/canopy/src/lib/alert/alert.component.ts, projects/canopy/src/lib/alert/docs/guide.stories.mdx
Currently, the variant setter code is unable to read the role input and automatically sets one. Subsequently, the role is read afterward and adjusted accordingly. Consequently, VoiceOver will behave according to the role set by the variant setter code, despite the role being changed immediately afterward.
=> Fix lg-alert role attibute not being read by VoiceOver

.storybook/main.js, projects/canopy/src/lib/carousel/carousel.component.html, projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.ts, projects/canopy/src/lib/carousel/docs/carousel.stories.ts
At the moment, one of the Carousel unit tests is failing due to how a transition is defined as an inline style.
To fix this, I had to remove the `ease` `transition-timing-property` from the inline style at line 16 in `projects/canopy/src/lib/carousel/carousel.component.html`, as it seems it's ignored by Angular due to being the default value for that property(this is an assumption). After doing this, I also had to update the related unit test case.
Using any other `transition-timing-property` value other than the default results in that value being visible in the DOM.
To test the transition fix of the carousel, I also had to fix a bug where the Storybook story of the accordion wasn't visible due to a missing configuration import in `.storybook/main.js`.
Also fixes some …
=> Fix carousel storybook documentation and unit tests

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/accordion/accordion-panel-heading/accordion-panel-heading.component.html, projects/canopy/src/lib/accordion/accordion-panel-heading/accordion-panel-heading.component.scss, projects/canopy/src/lib/accordion/accordion-panel-heading/accordion-panel-heading.component.ts
Fixes a visual bug where the text of the accordion panel heading overlaps the chevron icon when the text is long. This issue is visible on mobile devices.
Screenshot:
**Before**
**After**
=> Fix a visual bug of the accordion with decorative icon variant

projects/canopy/src/lib/breadcrumb/breadcrumb-item/breadcrumb-item.component.ts, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.ts, projects/canopy/src/lib/carousel/auto-play/auto-play.component.ts, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.ts, projects/canopy/src/lib/forms/select/select-field.component.ts, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/validation/validation.component.ts, projects/canopy/src/lib/header/header.component.ts, projects/canopy/src/lib/link-menu/link-menu-item/link-menu-item.component.ts, projects/canopy/src/lib/modal/modal-header/modal-header.component.ts, projects/canopy/src/lib/pagination/pagination.component.ts, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.ts, projects/canopy/src/lib/table/table-row-toggle/table-row-toggle.component.ts
Fixes #1470
I built Canopy locally and tested a component that used a `<lg-validation>` component. As a result, the icon could be seen in the user interface.
=> Add missing icons on certain components

projects/canopy/src/lib/banner/banner.component.html, projects/canopy/src/lib/banner/banner.component.scss, projects/canopy/src/lib/banner/docs/banner.stories.ts, projects/canopy/src/styles/variables.scss, projects/canopy/src/styles/variables/components/_banner.scss
- adds link colours to the banner message component so any links used in the projected content are contrast compliant
- adds a container to the projected content so links are aligned correctly (and to allow for dismiss functionality later)
- adds link text to the component example
Fixes #1417
=> Add link styles to banner message

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/modal/docs/guide.stories.mdx, projects/canopy/src/lib/modal/docs/modal.stories.ts, projects/canopy/src/lib/modal/modal.component.spec.ts, projects/canopy/src/lib/modal/modal.component.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX184JB2vDY0gmxRaAWtjwtQTMcPCD9N7ZE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=4DgSJj_)
Add a new input to the modal called `closeOnOverlayClick` to set wether the modal should close on click of the overlay or not. The new input is set to `true` by default so that it doesn't cause any breaking change.
**Input set to `true`:**
https://github.com/user-attachments/assets/c9969537-7f54-4e2c-a867-dadfafad1aa2
**Input set to `false`:**
https://github.com/user-attachments/assets/b14b118d-4767-4e2f-aeb8-a35bc9d4b772
=> feat(modal): add new input to handle overlay click

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/promo-card/docs/guide.stories.mdx, projects/canopy/src/lib/promo-card/docs/promo-card.stories.ts, projects/canopy/src/lib/promo-card/promo-card.interface.ts, projects/canopy/src/lib/promo-card/promo-card/promo-card.component.scss
Adds a new, `solid-yellow` colour variant to the Promo Card.
=> Add a new yellow variant to the Promo Card

.github/workflows/master_push.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX182nyRMqbmdAy86PLbbPVihDA6PQ27040%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=cMvz_hP)
The ui-icons-files and brand-icons-files folders that are generated when building the new icons, were not available for the master storybook build. Running the icons build before the deplyment fixes the issue
The deployment step for `master` requires the icons to be built so that the `ui-icons-files` and `brand-icons-files` folders within `projects/canopy/src/lib` are available for the Storybook build. This wasn't an issue before because we used to include the main generated file into the source - the new approach produces too …
=> ci(master-push): fixes issue when deploying from master

projects/canopy/src/lib/footer/footer-nav-item/footer-nav-item.component.ts
using firstChild selects comment nodes and therefore gives a console error when adding a class to it
There is a slight difference in where Angular renders the comment node (ie, the anchor for the view container) slightly differently in the @if(){}@else{} syntax compared to the `*ngIf(condition; else tpl)` syntax. 
That is, in the @else part, the first child is now the comment node which isn't the case with the explicit structural directive syntax. 
`LgFooterNavItemComponent` wants to get hold of the `a` element or `button` element then add a css class to it, `this.renderer.addClass(childEl, 'lg-footer-action');`. The else part errors as the firstChild returns the comment node, and tries to add a class to the comment node . 
Using the `firstElementChild` solves this issue, as it will gets …
=> fix(footer-nav-item): use firstElementChild

projects/canopy/src/lib/card/card.component.scss, projects/canopy/src/lib/card/docs/promotions/guide.stories.mdx, projects/canopy/src/lib/card/docs/promotions/promotions.stories.ts, projects/canopy/src/lib/shadow/docs/guide.stories.mdx, projects/canopy/src/lib/shadow/docs/shadow.stories.ts, projects/canopy/src/lib/shadow/shadow.directive.spec.ts, projects/canopy/src/lib/shadow/shadow.directive.ts, projects/canopy/src/styles/shadow.scss, projects/canopy/src/styles/variables/_main.scss
Canopy lgShadow directive added a box-shadow to its host component. However, the box-shadow value was from an older design. Canopy designs has a new desgin for drop shadows. Navigation cards already has the updated drop shadow styles. However, it hardcodes the value in .lg-card--navigation class. 
This PR:
- Updates the `--drop-shadow` CSS custom property the latest Canopy design box-shadow value
- Creates a new CSS custom property called `--box-shadow-hover` and sets its value to the latest Canopy drop shadow hover state value
- Updates .lg-card--navigation to use the `--drop-shadow` CSS custom property, instead of hardcoding it in the class. `box-shadow: var(--drop-shadow);`
- Updates .lg-card--navigation:hover to use the `--box-shadow-hover` CSS custom property, instead of hardcoding …
=> feat(lgshadow): update drop shadow to new design 

projects/canopy/src/lib/progress-indicator/progress-bar/progress-bar.component.html, projects/canopy/src/lib/progress-indicator/progress-bar/progress-bar.component.spec.ts
At the moment, the progress of the bar isn't reflected when the screen reader reads out the details of that element. This is because `aria-valuemin` doesn't represent the correct value. As a result, the percentage value read out will always be 0, since the same value is used for both `aria-valuemin` and `aria-valuenow` attributes.
**Before**
https://github.com/user-attachments/assets/cd4d84bd-b881-46bc-b3ed-16f7b1e1d0a5
- Sets `aria-valuemin` to 0, ensuring the progress bar percentage reflects the current step.
- Updates unit tests.
**After**
https://github.com/user-attachments/assets/adbeb450-ae76-4359-aeda-2ad4b9d752a5
=> Progress bar accessibility bug fix

projects/canopy/src/lib/header/primary-navigation/primary-navigation.component.scss
A recent accessibility audit raised an issue with not being able to scroll through the primary navigation items when testing at the small viewport 320x256. In our case it means the user cannot log out. This change allows scrolling when necessary so all navigation can be accessed.
WCAG guideline link - https://www.w3.org/WAI/WCAG21/Understanding/reflow.html
https://github.com/user-attachments/assets/72adeae3-bd81-4b6e-a060-f96af081ba9f
=> Make primary navigation scrollable for smaller screens

.github/dependabot.yml
Dependabot updates workflow contains a missing option (registries) that needs to be removed.
Design link: N/A
Screenshot: N/A
=> FEP-3867: Remove missing "registries" property from the Dependabot workflow

projects/canopy/src/lib/table/table/table.component.scss, projects/canopy/src/styles/list.scss
This PR includes a couple of fixes:
1. The striped variant of the table should have the grey on odd rows (raised on Slack and confirmed by Alex C.)
2. The colour of the counter on an ordered list with expressive variant is incorrect when using a different text colour
Fix: #1509
=> Fix stripes on table and colour of list counter

projects/canopy/src/lib/docs/welcome/welcome.stories.ts
Add wait for the welcome image as it doesn't always appear in the snapshots.
=> test(percy): add wait for selector to welcome page

projects/canopy/src/lib/footer/docs/footer.stories.ts, projects/canopy/src/lib/page/docs/page.stories.ts
The primaryLinks and secondaryLinks variables from `projects/canopy/src/lib/footer/docs/footer.stories.ts` were treated as real stories by Storybook, so they had to be excluded.
N/A
Design link: N/A
Screenshot: N/A
=> FEP-4285: Remove primary/secondary links from side-menu (components/footer)

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.html, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.scss, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.spec.ts, projects/canopy/src/lib/card/card-navigation-title/card-navigation-title.component.ts, projects/canopy/src/lib/card/docs/card/card.stories.ts, projects/canopy/src/lib/card/docs/card/guide.mdx
This PR adds the `target='_blank'` attribute for external links. It also changes the icon from and arrow to the external link one.
Using the card navigation title as an external link.
=> feat(card-navigation-title): add better handling of external links

projects/canopy/src/lib/button/button.component.scss
Update incorrect 'link' button font weight.
Fixes: #1562
=> fix: button link font weight

.github/workflows/branch_pages_deploy.yml, .github/workflows/master_push.yml
Update workflows to use different `PERCY_TOKEN` based on the branch (whether it's brand modernisation or not).
We have two different instances of Percy; one for our main library and one for the brand modernisation work. 
The correct token must be used.
=> ci(brand-modernisation): update workflows
