package-lock.json
=> fix: update selfsigned transient dependency

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.html, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.scss, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.spec.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.component.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.module.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.notes.ts, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.stories.ts, projects/canopy/src/lib/forms/checkbox-group/index.ts, projects/canopy/src/lib/forms/forms.module.ts, projects/canopy/src/lib/forms/radio/radio-group.component.spec.ts, projects/canopy/src/lib/forms/radio/radio-group.component.ts, projects/canopy/src/lib/forms/toggle/toggle.component.scss, projects/canopy/src/lib/forms/toggle/toggle.component.ts, projects/canopy/src/lib/forms/validation/form.stories.ts
Adds checkbox-group component.
Screenshot:
=> feat(checkbox-group): adds checkbox group

projects/canopy-test-app/src/app/app.component.html, projects/canopy-test-app/src/app/app.component.ts, projects/canopy/src/lib/forms/date/date-field.component.html, projects/canopy/src/lib/forms/date/date-field.module.ts, projects/canopy/src/lib/forms/forms.module.ts, projects/canopy/src/lib/forms/index.ts, projects/canopy/src/lib/forms/input/input-field.component.spec.ts, projects/canopy/src/lib/forms/input/input-field.component.ts, projects/canopy/src/lib/forms/sort-code/index.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.html, projects/canopy/src/lib/forms/sort-code/sort-code.component.scss, projects/canopy/src/lib/forms/sort-code/sort-code.component.spec.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.ts, projects/canopy/src/lib/forms/sort-code/sort-code.interface.ts, projects/canopy/src/lib/forms/sort-code/sort-code.module.ts, projects/canopy/src/lib/forms/sort-code/sort-code.notes.ts, projects/canopy/src/lib/forms/sort-code/sort-code.stories.ts, projects/canopy/src/lib/forms/validation/form.stories.ts
Creates a new Sort Code component, based on the current Date Field component.
Also fixes a couple of issues found with the Date Field (and also Sort Code) component (see other commits).
Please test the component as normal and also validation rules as part of a form, for example the Validation Form story.
Screenshot:
=> Sort code field

projects/canopy/src/lib/card/card-subtitle/card-subtitle.component.scss
To the best of my knowledge there hasn't been an 'xs' small breakpoint so I believe this code wasn't doing anything. We may need to re-visit the card design in the future but this should help to keep the logs clean for now.
fix #76
Screenshot: No visual changes
=> refactor(card): removes redundant css

projects/canopy/src/lib/table/table-cell/table-cell.component.scss, projects/canopy/src/lib/table/table.stories.ts
I have added a table with input field example to Storybook, this should help to document the pattern which first highlighted the issue. The fix is a simple line of css but I wanted to add the example to get some design eyes on the pattern to make sure we are doing it right. (cc @alexcanning)
Fixes # #108
=> Tabel cell - vertical alignment fix

projects/canopy/src/lib/hero/hero-card-notification/hero-card-notification.component.scss, projects/canopy/src/lib/hero/hero-header/hero-header.component.scss
Allows breadcrumb items in hero header to be clickable.
Allows links in hero notifications panel to be clickable
Fixes #158
Browse to the test app and ensure the breadcrumb items in the hero header can be clicked/selected
Browse to the hero product details page and ensure the contact us link in the notifications panel can be clicked
Storybook link: https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/test-page--standard
https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/components-hero--product-details
Screenshot:
=> fix(hero): ensure content is clickable

projects/canopy/package.json
Updated the peer-dependencies in [projects/canopy/package.json](https://github.com/Legal-and-General/canopy/blob/master/projects/canopy/package.json) from 10.0.10 to 11.1.0
=> build(package.json): updated peer-dependencies to angular 11.1.0

projects/canopy/src/lib/grid/grid.notes.ts, projects/canopy/src/lib/header/header.notes.ts, projects/canopy/src/lib/heading/heading.notes.ts, projects/canopy/src/lib/hero/hero.notes.ts, projects/canopy/src/lib/hero/hero.stories.ts, projects/canopy/src/lib/tabs/tabs.notes.ts
Fixes a few issues and build errors I noticed when copying and pasting code snippets from the notes of some components. 
Also improves the Hero docs by splitting the breadcrumb example out into it's own dedicated snippet.
~Note that the commit message doesn't contain the optional scope - as I couldn't think of what the scope should be. If you think it could do with a scope, let me know.~ This has now been split into individually scoped commits
All code snippets should be copy and pasted easily without errors.
=> docs: correct errors and other issues in notes and stories

projects/canopy/src/lib/pipes/camel-case/camel-case.pipe.ts
Fix code scanning issue: insufficient regular expression.
For more details:
https://github.com/Legal-and-General/canopy/pull/194/checks?check_run_id=1823669882
=> fix(camel-case-pipe): update regex to fix code scanning issue

projects/canopy/src/lib/promo-card/promo-card.stories.ts, projects/canopy/src/lib/promo-card/promo-card/promo-card.component.scss
Added a fix for Canopy promo cards not having the same width in a column layout.
Fixes #227 
=> Promo cards

.github/workflows/codeql_analysis.yml
Github Advanced Security is currently not running properly. The push event is always failing and the pull request one is not running on any file.
This PR fixes the events of the workflow not being setup correctly.
=> ci(ghas): update configuration for ghas

projects/canopy/src/lib/card/card.component.scss, projects/canopy/src/lib/card/card.stories.ts, projects/canopy/src/lib/shadow/index.ts, projects/canopy/src/lib/shadow/shadow.directive.spec.ts, projects/canopy/src/lib/shadow/shadow.directive.ts, projects/canopy/src/lib/shadow/shadow.module.ts, projects/canopy/src/lib/shadow/shadow.notes.ts, projects/canopy/src/lib/shadow/shadow.stories.ts, projects/canopy/src/public-api.ts, projects/canopy/src/styles/shadow.scss, projects/canopy/src/styles/styles.scss
Removes the default shadow from the card component
Fixes #277
Storybook link: https://deploy-preview-349--legal-and-general-canopy.netlify.app
=> feat(shadow): adds shadow directive

projects/canopy/src/lib/card/card.component.scss, projects/canopy/src/lib/side-nav/index.ts, projects/canopy/src/lib/side-nav/side-nav-bar-footer/side-nav-bar-footer.component.scss, projects/canopy/src/lib/side-nav/side-nav-bar-footer/side-nav-bar-footer.component.ts, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.html, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.scss, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.ts, projects/canopy/src/lib/side-nav/side-nav-bar-link/side-nav-bar-link.directive.spec.ts, projects/canopy/src/lib/side-nav/side-nav-bar-link/side-nav-bar-link.directive.ts, projects/canopy/src/lib/side-nav/side-nav-bar/side-nav-bar.component.html, projects/canopy/src/lib/side-nav/side-nav-bar/side-nav-bar.component.scss, projects/canopy/src/lib/side-nav/side-nav-content/side-nav-content.component.scss, projects/canopy/src/lib/side-nav/side-nav.component.scss, projects/canopy/src/lib/side-nav/side-nav.component.ts, projects/canopy/src/lib/side-nav/side-nav.module.ts, projects/canopy/src/lib/side-nav/side-nav.notes.ts, projects/canopy/src/lib/side-nav/side-nav.stories.ts, projects/canopy/src/styles/mixins.scss, projects/canopy/src/styles/variables/components/_side-nav.scss
This PR adds the correct layout and styling to the Side Nav Bar component.
Storybook link: https://deploy-preview-352--legal-and-general-canopy.netlify.app
=> refactor(side-nav): adds side nav cards

projects/canopy/src/lib/card/card.component.scss, projects/canopy/src/lib/side-nav/index.ts, projects/canopy/src/lib/side-nav/side-nav-bar-footer/side-nav-bar-footer.component.scss, projects/canopy/src/lib/side-nav/side-nav-bar-footer/side-nav-bar-footer.component.ts, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.html, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.scss, projects/canopy/src/lib/side-nav/side-nav-bar-item/side-nav-bar-item.component.ts, projects/canopy/src/lib/side-nav/side-nav-bar-link/side-nav-bar-link.directive.spec.ts, projects/canopy/src/lib/side-nav/side-nav-bar-link/side-nav-bar-link.directive.ts, projects/canopy/src/lib/side-nav/side-nav-bar/side-nav-bar.component.html, projects/canopy/src/lib/side-nav/side-nav-bar/side-nav-bar.component.scss, projects/canopy/src/lib/side-nav/side-nav-content/side-nav-content.component.scss, projects/canopy/src/lib/side-nav/side-nav.component.scss, projects/canopy/src/lib/side-nav/side-nav.component.ts, projects/canopy/src/lib/side-nav/side-nav.module.ts, projects/canopy/src/lib/side-nav/side-nav.notes.ts, projects/canopy/src/lib/side-nav/side-nav.stories.ts, projects/canopy/src/styles/mixins.scss, projects/canopy/src/styles/variables/components/_side-nav.scss
This PR adds the correct layout and styling to the Side Nav Bar component.
Storybook link: https://deploy-preview-359--legal-and-general-canopy.netlify.app
=> fix(side-nav): adds side nav cards

projects/canopy/src/lib/promo-card/promo-card-list/promo-card-list-title/promo-card-list-title.component.html, projects/canopy/src/lib/promo-card/promo-card-list/promo-card-list-title/promo-card-list-title.component.scss, projects/canopy/src/lib/promo-card/promo-card/promo-card-title/promo-card-title.component.html, projects/canopy/src/lib/promo-card/promo-card/promo-card-title/promo-card-title.component.scss
Fixes some incorrect styling on the headings for the Promo Card component.
Ensure the Promo Card component appears correctly.
=> fix(promo-card): ensure correct styling for headings

projects/canopy-test-app/src/app/app.component.html, projects/canopy/src/lib/carousel/auto-play/auto-play.component.html, projects/canopy/src/lib/carousel/auto-play/auto-play.component.scss, projects/canopy/src/lib/carousel/auto-play/auto-play.component.spec.ts, projects/canopy/src/lib/carousel/auto-play/auto-play.component.ts, projects/canopy/src/lib/carousel/carousel.component.html, projects/canopy/src/lib/carousel/carousel.component.scss, projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.ts, projects/canopy/src/lib/carousel/carousel.module.ts, projects/canopy/src/lib/carousel/carousel.notes.ts, projects/canopy/src/lib/carousel/carousel.stories.ts, projects/canopy/src/styles/variables/_main.scss
Added optional autoPlay mode to Carousel component. This adds a timer with pause and play button to give control to the user. AutoplayDelay is a parameter that can be defined to set the timer.
Design link: https://legalandgeneral.invisionapp.com/overview/Canopy-Carousel-ckou4o2im00m9013db6ww6lfv/screens?share=&sortBy=1&sortOrder=1&viewLayout=2
Screenshot: https://www.awesomescreenshot.com/video/4219164?key=a2993ad195e64c47115859e396c26b28
=> feat(auto play carousel): added auto play carousel feature

projects/canopy/src/lib/modal/index.ts, projects/canopy/src/lib/modal/modal.module.ts, projects/canopy/src/lib/modal/modal.notes.ts
This fix the following issue:
```
Module not found: Error: Can't resolve '@legal-and-general/canopy/lib/modal/modal.module'
```
And also update the notes which were formatted incorrectly.
=> Fix issue with modal module not being available

projects/canopy/src/lib/accordion/accordion-item/accordion-item.component.ts, projects/canopy/src/lib/brand-icon/brand-icon.component.ts, projects/canopy/src/lib/button/button.component.scss, projects/canopy/src/lib/card/card-footer/card-footer.component.spec.ts, projects/canopy/src/lib/carousel/carousel.component.spec.ts, projects/canopy/src/lib/feature-toggle/feature-toggle.directive.ts, projects/canopy/src/lib/feature-toggle/feature-toggle.guard.spec.ts, projects/canopy/src/lib/modal/modal-body-timer/modal-body-timer.component.html
**Test file changes**
- card-footer.component.spec.ts
Removed the deprecated async() and replaced it with waitForAsync()
- carousel.component.spec.ts
Extracted the duplicated logic and placed it inside a function expression which gets called in multiple places
- feature-toggle.guard.spec.ts 
Created a separate enum to check for guard type when testing and the duplicated logic was placed inside a function expression which gets tweaked with different parameters that cater to the different test cases
**Style file changes**
-accordion-panel-heading.component.scss 
A simple class nesting change 
-button.component.scss 
Used the short-hand version of : top,left,right,bottom: 0 -> inset: 0 
**Directive file changes**
-feature-toggle.directive.ts 
Used the optional chaining operator and removed …
=> refactor: remove duplicate code from unit tests

projects/canopy/src/lib/header/header.component.scss
=> fix(header): removes link hover style from header logo

projects/canopy/src/lib/forms/date/date-field.component.ts, projects/canopy/src/lib/forms/date/date-field.notes.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.spec.ts, projects/canopy/src/lib/forms/sort-code/sort-code.component.ts, projects/canopy/src/lib/forms/sort-code/sort-code.notes.ts
Update sort code validation as it wasn't working correctly and add notes on how to make the validation fully work when using the component. The notes have also been updated for the `date-field`.
Also add unsubscription for existing subscriptions.
=> Update sort-code validation

.storybook/main.js, documentation.json, projects/canopy/src/lib/details/details.component.ts, projects/canopy/src/lib/details/details.notes.ts, projects/canopy/src/lib/details/details.stories.ts
Upgrades the Details component to use the new CSF format.
=> feat(details): upgrade to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/accordion/accordion.notes.ts, projects/canopy/src/lib/alert/alert.stories.ts, projects/canopy/src/lib/footer/footer.notes.ts, projects/canopy/src/lib/footer/footer.stories.ts, projects/canopy/src/lib/header/header.notes.ts, projects/canopy/src/lib/header/header.stories.ts, projects/canopy/src/lib/heading/heading.notes.ts, projects/canopy/src/lib/heading/heading.stories.ts
Update heading component to CSF format.
Update header component to CSF format.
Update footer component to CSF format.
=> Upgrade heading, header and footer to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/icon/icon.notes.ts, projects/canopy/src/lib/icon/icons.stories.ts
Upgrades the Icon story to CSF format. Makes the Icon story work in Storybook v6.
=> docs(icon): upgrade to CSF format

.storybook/main.js, .storybook/preview-head.html, documentation.json, projects/canopy/src/lib/breadcrumb/breadcrumb.notes.ts, projects/canopy/src/lib/breadcrumb/breadcrumb.stories.ts
Updates the Breadcrumb component to work in Storybook v6.
=> feat(breadcrumb): upgrade to CSF format

.storybook/main.js, documentation.json, package-lock.json, projects/canopy/src/lib/carousel/carousel.notes.ts, projects/canopy/src/lib/carousel/carousel.stories.ts
Updates the Carousel component to work in Storybook v6.
https://user-images.githubusercontent.com/8397116/146031488-6cdb7485-4797-406f-9cbd-b3ed00bbde0b.mov
=> Update carousel story to new format

.storybook/main.js, documentation.json, projects/canopy/src/lib/variant/variant.notes.ts, projects/canopy/src/lib/variant/variant.stories.ts
Updates the Variant Directive story to work with Storybook v6.
=> docs(variant): update to CSF format for Storybook v6

.storybook/main.js, .storybook/preview-head.html, .storybook/preview.js, documentation.json, projects/canopy/src/lib/card/card.notes.ts, projects/canopy/src/lib/card/card.stories.ts
Update card story to CSF format.
=> docs(card): update story to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/accordion/accordion.stories.ts, projects/canopy/src/lib/card/card.notes.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts, projects/canopy/src/lib/forms/radio/radio.notes.ts, projects/canopy/src/lib/spinner/spinner.notes.ts, projects/canopy/src/lib/spinner/spinner.stories.ts
Update filter buttons and spinner stories to CSF format.
Also fixes accordion not working.
=> Storybook update of filter buttons and spinner

.storybook/main.js, documentation.json, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.notes.ts, projects/canopy/src/lib/forms/checkbox-group/filter-group.stories.ts, projects/canopy/src/lib/forms/radio/filter.stories.ts
Update filter group buttons story to CSF format.
=> Update filter group buttons story to CSF format

projects/canopy/src/lib/header/header.component.scss
Increase margin between two logos.
=> fix(header): update margin for second logo

.storybook/main.js, documentation.json, projects/canopy/src/lib/hero/hero.notes.ts, projects/canopy/src/lib/hero/hero.stories.ts
Update Hero component to CSF story.
=> docs(hero): update story to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/shadow/shadow.stories.ts
Upgrade Shadow directive to CSF format
=> docs(shadow): upgrade to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/forms/checkbox-group/checkbox-group.stories.ts
Upgrade checkbox group story to CSF format
=> docs(checkbox-group): upgrade to CSF format

projects/canopy/src/lib/hero-img/hero-img-card/hero-img-card.component.scss
Update colour variable for hero image card
Update Hero Image Card colour variable as was broken
=> fix(hero-img-card): variable update

.storybook/main.js, documentation.json, projects/canopy/src/lib/page/page.notes.ts, projects/canopy/src/lib/page/page.stories.ts
Update Page story to CSF format.
=> docs(page): update to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/forms/input/input.notes.ts, projects/canopy/src/lib/forms/input/input.stories.ts
Update input story to CSF format.
=> docs(input): update to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/forms/validation/validation.component.ts, projects/canopy/src/lib/forms/validation/validation.module.ts, projects/canopy/src/lib/forms/validation/validation.notes.ts, projects/canopy/src/lib/forms/validation/validation.stories.ts
Update validation story to CSF format.
Also add the Variant module to the validation module and update the default value of the variant from `null` to `undefined`.
=> Update validation story to CSF format

projects/canopy/src/lib/pipes/index.ts
This PR removes unused **pipe.module** file and fixes the imports of the **pipe** modules.
=> fix(pipes): add module exports for existing pipes

.storybook/main.js, documentation.json, projects/canopy/src/lib/forms/validation/form.notes.ts, projects/canopy/src/lib/forms/validation/form.stories.ts, projects/canopy/src/lib/side-nav/side-nav.notes.ts, projects/canopy/src/lib/side-nav/side-nav.stories.ts, projects/canopy/src/lib/tabs/tab-nav-bar.stories.ts, projects/canopy/src/lib/tabs/tabs.notes.ts, projects/canopy/src/lib/tabs/tabs.stories.ts
Update form validation, side nav and tabs stories to CSF format
=> Update form validation, side nav and tabs stories to CSF format

.storybook/main.js, documentation.json, projects/canopy/src/lib/grid/grid.notes.ts, projects/canopy/src/lib/grid/grid.stories.ts, projects/canopy/src/lib/table/table.notes.ts, projects/canopy/src/lib/table/table.stories.ts
Update table and grid directive to CSF format
=> Update table and grid directive to CSF format

.github/pull_request_template.md, .storybook/main.js, README.md, docs/USAGE.md, projects/canopy/src/lib/intro.stories.mdx
Add landing page to Storybook - for now this matches the GitHub `README.md` but in the future we'll update it to include more information about components, design, etc.
Also slightly update some outdated documentation.
https://user-images.githubusercontent.com/8397116/165084642-360cdfca-940a-4b56-8533-4fef7d3c6bce.mov
=> Add landing page to Storybook

.github/workflow-scripts/gh-pages/undeploy.js
Fix issue with getting the branches to un-deploy.
=> fix(gh-pages): update getting the environments to un-deployed

.github/workflow-scripts/gh-pages/deploy.js
This is becoming my worst nightmare.
=> docs(gh-pages): add missing await

package-lock.json, package.json, webpack.global.config.js
This PR was created by the Combine Dependabot PRs action by combining the following PRs:
**Wed Jul 27 2022**
- #964
**Mon Aug 01 2022**
- #971
- #970
**Mon Aug 08 2022**
- #976
- #975
- #974
- #968
- #965
=> Combined dependency updates

projects/canopy/src/lib/docs/principles/writing.stories.mdx
Update the writing principles page to add a section for error messaging content.
=> docs(writing): add error messaging section

projects/canopy/src/lib/accordion/docs/guide.stories.mdx, projects/canopy/src/lib/alert/docs/guide.stories.mdx, projects/canopy/src/lib/breadcrumb/docs/guide.stories.mdx, projects/canopy/src/lib/button/docs/guide.stories.mdx, projects/canopy/src/lib/card/docs/guide.stories.mdx, projects/canopy/src/lib/details/docs/guide.stories.mdx, projects/canopy/src/lib/docs/common/feedback.md, projects/canopy/src/lib/docs/foundation/colours/colours.stories.mdx, projects/canopy/src/lib/docs/foundation/typography/typography.stories.mdx, projects/canopy/src/lib/docs/principles/writing.stories.mdx, projects/canopy/src/lib/forms/docs/filter-buttons/guide.stories.mdx, projects/canopy/src/lib/icon/docs/guide.stories.mdx, projects/canopy/src/lib/modal/docs/guide.stories.mdx, projects/canopy/src/lib/quick-action/docs/guide.stories.mdx, projects/canopy/src/lib/separator/docs/guide.stories.mdx, projects/canopy/src/lib/spinner/docs/guide.stories.mdx
Update feedback section of the docs to be reusable.
=> docs(feedback): make section reusable and update existing docs

projects/canopy/src/styles/blockquote.stories.mdx
Merged but forgot to have Alex review it. He just requested this change
=> docs(blockquote): update standfirst

projects/canopy/src/lib/pipes/kebab-case/kebab-case.pipe.spec.ts, projects/canopy/src/lib/pipes/kebab-case/kebab-case.pipe.ts
Updated the KebabCase pipe to include a wider variety of cases to kebab.
Automation should cover the testing, outside of disagreeing with test cases.
=> feat(pipes): improved kebab-case pipe

projects/canopy/src/lib/pagination/pagination.component.html
Add accessibility  for pagination label  
=> fix: add accesibillity for pagination label

projects/canopy/src/lib/card/card.module.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18g2rb2Q9zFHRdnswIpYJSm8vQhxkdQUVc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=L08Zrem)
Update RouterLinkWithHref to RouterLink
=> FEP-1471: update RouterLinkWithHref to RouterLink

docs/CODE_OF_CONDUCT.md, docs/SECURITY.md, projects/canopy/src/lib/accordion/accordion-item/accordion-item.component.scss, projects/canopy/src/lib/accordion/accordion-panel-heading/accordion-panel-heading.component.scss, projects/canopy/src/lib/details/details-panel-heading/details-panel-heading.component.scss, projects/canopy/src/lib/details/details.component.scss, projects/canopy/src/lib/forms/input/input-field.component.scss, projects/canopy/src/lib/forms/radio/radio-button--segment.component.scss, projects/canopy/src/lib/forms/radio/radio-button.component.scss, projects/canopy/src/lib/forms/select/select.scss, projects/canopy/src/lib/table/table-row-toggle/table-row-toggle.component.scss, projects/canopy/src/styles/variables/components/_hero.scss
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX186TmysDmqAH8QjG212m3fpi0I30TkrRg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Or8mfQW)
The focus state of the following components have been changed to match the new style (yellow and black outline):
- Accordion
- Details
- Forms (text input, segment, select)
- Table (expandable details)
- Hero notification links
=> FEP-710: Update focus state

projects/canopy/src/lib/orientation/index.ts, projects/canopy/src/public-api.ts
OPT-1976
Add Orientation API to the public-api file.
=> fix(orientation): add orientation directive to public api

projects/canopy/src/styles/variables/_typography.scss
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19q52qyG4dp8FbVUKtK3HckWqWgomI5uA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=yiBT7GM)
Reduce line height of some type styles (some of them are not 100% exact but very close as couldn't get the correct value using the line heights numbers).
Please see the discussion for more details: https://github.com/Legal-and-General/canopy/discussions/1174
In addition to that, it updated the `font-size-7` on small devices that was incorrectly set to 48px instead of 52px.
Resolves #1174 
See requirements in https://github.com/Legal-and-General/canopy/discussions/1174.
Design link: …
=> Reduce line height of some type styles

projects/canopy/src/lib/utils/index.ts, projects/canopy/src/public-api.ts
As this service is quite useful even outside Canopy, an export via the public API has been created.
=> Export DomService through the public-api

projects/canopy/src/lib/icon/icons.interface.ts
This PR removes the broken `question-mark` icon which already exists under the name `query-fill`
=> fix(ui-icons): remove question-mark icon

projects/canopy/src/styles/variables/_main.scss, projects/canopy/src/styles/variables/_variants.scss
Fixes [Visited links do not have a specified color](https://github.com/Legal-and-General/canopy/issues/1507)
=> Fix visited links color

.github/workflows/branch_pages_deploy.yml, .github/workflows/master_push.yml
Add specific path to config in Percy command.
=> test(percy): specify config file

.github/workflow-scripts/gh-pages/deploy.js, .github/workflows/master_push.yml, .percy.yml
Fixes an issue with master not picking up the correct configuration.
Also add config to exclude hidden docs stories.
=> FEP-4266: amendments to visual testing workflows

projects/canopy/src/lib/button/button.component.scss
Please include a summary of the change and if appropriate which issue(s) it fixes. Where possible explain the rationale behind the implementation especially if it brings in new patterns or approaches.
https://github.com/Legal-and-General/canopy/issues/1565
=> fix(button): align button link text to start

.github/workflow-scripts/gh-pages/deploy.js, .github/workflows/master_push.yml, .releaserc
Update the deployment and release workflows for master-bm, the brand modenisation branch.
Make the relevant changes so that we can deploy the master-bm branch to Storybook and and new package is created on merge to the master-bm branch
=> feat(brand modernisation setup): deployment and release workflows

.github/workflow-scripts/gh-pages/deploy.js, .github/workflows/master_push.yml
Fix a couple of issue to do with the logic of the `master-BM` branch.
Also slightly refactors the `deploy.js`.
=> Fix issues with BM logic in Percy and deploy

.github/workflow-scripts/gh-pages/deploy.js
Update the `deploy.js` code:
- refactors if/else statement to make the code more readable.
- fixes an issue with the deployment of the `master-bm` branch; this wasn't working because the files were never moved in the correct subfolder.
=> ci(brand-modernisation): fix deploy logic

README.md
Update the readme file for the brand modernisation branch and link to the branch Storybook
Add a change to the readme to mention the brand modernisation work and a link to the Storybook environment (legal-and-general.github.io/canopy/lg-sb-master-bm?path=/docs/welcome--docs)
=> feat(brand modernisation readme): update readme file
